load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "telemetry",
    srcs = ["telemetry.go"],
    importpath = "github.com/recurser/bossd/internal/telemetry",
    visibility = ["//services/bossd:__subpackages__"],
    deps = [
        "//lib/bossalib/config",
        "//lib/bossalib/safego",
        "//lib/bossalib/telemetry",
        "@com_github_rs_zerolog//:zerolog",
    ],
)

go_test(
    name = "telemetry_test",
    srcs = [
        "capture_test.go",
        "telemetry_test.go",
    ],
    embed = [":telemetry"],
    deps = [
        "//lib/bossalib/config",
        "//lib/bossalib/telemetry",
    ],
)
