load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "hostclient",
    srcs = ["hostclient.go"],
    importpath = "github.com/recurser/bossalib/plugin/hostclient",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/bossalib/gen/bossanova/v1:bossanova",
        "@com_github_hashicorp_go_plugin//:go-plugin",
        "@com_github_rs_zerolog//:zerolog",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_test(
    name = "hostclient_test",
    srcs = ["hostclient_test.go"],
    embed = [":hostclient"],
    deps = [
        "//lib/bossalib/gen/bossanova/v1:bossanova",
        "@com_github_rs_zerolog//:zerolog",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//test/bufconn",
        "@org_uber_go_goleak//:goleak",
    ],
)
