load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "models",
    srcs = [
        "account.go",
        "convert.go",
        "cron_job.go",
        "models.go",
        "workflow.go",
    ],
    importpath = "github.com/recurser/bossalib/models",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/bossalib/gen/bossanova/v1:bossanova",
        "//lib/bossalib/machine",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)

go_test(
    name = "models_test",
    srcs = ["convert_test.go"],
    embed = [":models"],
    deps = [
        "//lib/bossalib/gen/bossanova/v1:bossanova",
        "//lib/bossalib/machine",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
