load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "email",
    srcs = [
        "email.go",
        "noop.go",
        "resend.go",
    ],
    importpath = "github.com/recurser/bossalib/email",
    visibility = ["//visibility:public"],
    deps = ["@com_github_rs_zerolog//log"],
)

go_test(
    name = "email_test",
    srcs = ["resend_test.go"],
    embed = [":email"],
)
