package broadcast

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/rs/zerolog"

	bcast "github.com/recurser/bossalib/broadcast"
	"github.com/recurser/bossalib/machine"
	"github.com/recurser/bossalib/models"
	"github.com/recurser/bossalib/sqlutil"
)

// Class is the coarse outcome class a session state falls into: the vocabulary a
// standing subscription reasons about, deliberately narrower than the fourteen
// session states.
//
// A Class is what a STATE produces; models.BroadcastTrigger is what a
// SUBSCRIPTION asks for. They are not the same vocabulary — `settled` is a
// trigger with no corresponding class, because no state means "either" — so the
// two are related by Class.Matches rather than by a shared type.
type Class string

const (
	// ClassCompleted is a successful outcome: the session got where it was going.
	ClassCompleted Class = "completed"
	// ClassErrored is a failed or abandoned outcome.
	ClassErrored Class = "errored"
)

// Matches reports whether a subscription registered for trigger should fire on
// this outcome class. `settled` matches BOTH classes — that is the whole point of
// it ("tell me when it is over, whatever happened") — and an unknown trigger
// matches neither, so a row that somehow escaped validation stays silent rather
// than firing on everything.
func (c Class) Matches(trigger models.BroadcastTrigger) bool {
	switch trigger {
	case models.BroadcastTriggerCompleted:
		return c == ClassCompleted
	case models.BroadcastTriggerErrored:
		return c == ClassErrored
	case models.BroadcastTriggerSettled:
		return c == ClassCompleted || c == ClassErrored
	default:
		return false
	}
}

// TriggerClassFor maps a session state onto the outcome class it expresses, and
// reports whether the state is a trigger at all. This is the single state ->
// class table for the whole daemon.
//
//   - completed: Merged, ReadyForReview, GreenDraft, Closed — the session reached
//     an outcome a waiting coordinator would call "done". Closed counts as
//     completed rather than errored: closing a PR is a decision, not a failure.
//   - errored:   Blocked, Orphaned — the session stopped without an outcome.
//   - neither:   every in-flight state (CreatingWorktree … Finalizing). Finalizing
//     is deliberately NOT a trigger: it is the work of settling, not the settled
//     result, and the state it lands in fires.
//
// The switch is exhaustive on purpose and has no `default` that silently
// swallows: a newly added machine.State fails the compile-time-adjacent
// exhaustiveness guard in subscription_test.go instead of quietly never firing.
func TriggerClassFor(state machine.State) (Class, bool) {
	switch state {
	case machine.Merged, machine.ReadyForReview, machine.GreenDraft, machine.Closed:
		return ClassCompleted, true
	case machine.Blocked, machine.Orphaned:
		return ClassErrored, true
	case machine.CreatingWorktree, machine.StartingAgent, machine.PushingBranch,
		machine.OpeningDraftPR, machine.ImplementingPlan, machine.AwaitingChecks,
		machine.FixingChecks, machine.Finalizing:
		return "", false
	}
	// Unreachable for any classified state. An unrecognised value (a state added
	// without being classified above) fires nothing — the safe direction — and
	// TestTriggerClassForIsExhaustive is what makes that a loud, visible decision
	// rather than a silent one.
	return "", false
}

// SubscriptionBroadcast is the request the evaluator hands its sender: one
// broadcast, derived from one fired subscription.
//
// ID is generated by the EVALUATOR, not by the sender. MarkFired must record the
// broadcast id, and the CAS has to happen before the send (see
// SubscriptionEvaluator.fire), so the id cannot come back out of the send —
// it is minted up front and passed to both.
//
// Message is a SECRET body: it exists on this struct because a send needs it,
// and must never reach a log line, an error string, or a persisted diagnostic.
type SubscriptionBroadcast struct {
	// ID is the pre-generated broadcast id; the sender must persist the broadcast
	// under exactly this id so the subscription's fired_broadcast_id resolves.
	ID string
	// SubscriptionID is the subscription that fired, for logging and diagnostics.
	// Safe to log.
	SubscriptionID string
	// Selector is the parsed audience, validated before the CAS.
	Selector bcast.Selector
	// Message is the SECRET body to deliver.
	Message string
	// OriginChatID is the chat that registered the subscription, or "" when it was
	// operator-issued. It is PROVENANCE ONLY and never narrows the audience: the
	// selector alone decides who is told. Unlike an explicit send — where the
	// origin is the sender and is excluded so it does not wake itself — the
	// origin of a subscription is the requester, so excluding it would drop the
	// one chat that asked to be told (see Sender.SendBroadcast).
	OriginChatID string
	// ExpiresAt bounds the fired broadcast's own delivery window. It is derived
	// from the evaluator's clock, NOT inherited from the subscription: the
	// subscription's expiry bounds how long the rule stands, while this bounds how
	// long the resulting message is worth delivering, and a subscription that
	// fires one second before it expires must still get a full delivery window.
	ExpiresAt time.Time
}

// FiredBroadcastExpiry is the delivery window given to a broadcast a
// subscription fires. It matches the default expiry of an explicitly sent
// broadcast (githubcallback.ParseDuration's empty-string default), so a fired
// message is not treated differently from a hand-sent one.
const FiredBroadcastExpiry = 24 * time.Hour

// subscriptionStore is the subset of db.SQLiteBroadcastSubscriptionStore the
// evaluator uses. Narrowed here (rather than taking the concrete store) for the
// same reason callback.Evaluator and the broadcast delivery worker narrow
// theirs: it keeps the dependency honest and lets a test drive the CAS with a
// fake instead of a migrated database.
type subscriptionStore interface {
	ListActiveForSession(ctx context.Context, sessionID string) ([]models.BroadcastSubscription, error)
	MarkFired(ctx context.Context, id string, broadcastID string, now time.Time) (bool, error)
	ExpireOverdue(ctx context.Context, now time.Time) (int64, error)
	ListActiveOwnerSessionIDs(ctx context.Context) ([]string, error)
}

// broadcastSender resolves a subscription's audience and records the broadcast
// plus its deliveries — the same work SendBroadcast does for an explicit send.
// The evaluator never touches the resolver or the broadcast store directly, so
// the "subscriptions are a thin layer over the existing delivery path" claim is
// structural rather than aspirational.
type broadcastSender interface {
	SendBroadcast(ctx context.Context, b SubscriptionBroadcast) error
}

// sessionStateReader reads a session's CURRENT persisted state. Only used by the
// reconcile sweep; db.SQLiteSessionStore satisfies it.
type sessionStateReader interface {
	Get(ctx context.Context, id string) (*models.Session, error)
}

// SubscriptionEvaluator fires standing broadcast subscriptions when their owning
// session reaches an outcome matching their trigger.
//
// Exactly-once is the whole contract: a session can be transitioned from more
// than one code path and the reconcile sweep runs alongside them, so every fire
// goes through the store's MarkFired compare-and-swap BEFORE the send, and only
// the winner sends.
type SubscriptionEvaluator struct {
	subs     subscriptionStore
	sender   broadcastSender
	sessions sessionStateReader
	now      func() time.Time
	logger   zerolog.Logger
}

// NewSubscriptionEvaluator constructs a SubscriptionEvaluator. now may be nil
// (defaults to time.Now).
//
// The session reader used by ReconcileAll is supplied separately through
// WithSessionStates: OnSessionState — the hot path — is already told which
// session transitioned and needs no lookup, so requiring one here would make
// every caller wire a dependency only the sweep uses.
func NewSubscriptionEvaluator(subs subscriptionStore, sender broadcastSender, now func() time.Time, logger zerolog.Logger) *SubscriptionEvaluator {
	if now == nil {
		now = time.Now
	}
	return &SubscriptionEvaluator{subs: subs, sender: sender, now: now, logger: logger}
}

// WithSessionStates supplies the session lookup ReconcileAll needs and returns
// the evaluator for chaining. Without it ReconcileAll still expires overdue rows
// but reports the missing wiring as an error rather than going quietly inert.
func (e *SubscriptionEvaluator) WithSessionStates(sessions sessionStateReader) *SubscriptionEvaluator {
	e.sessions = sessions
	return e
}

// OnSessionState fires every live subscription on sessionID whose trigger
// matches the class of state `to`. Not a trigger state means no work at all.
//
// It reports what went wrong but is best-effort by CONTRACT OF ITS CALLER: a
// subscription failure must never fail or roll back the session transition
// itself, so the transition hook DISCARDS this error and continues.
//
// Because the hook discards it, this function is the last place a hot-path
// failure can become visible, so it logs before returning. Logging here rather
// than at each append site inside fire is what makes that total: a failed list
// (one unparseable row poisons every subscription on the session), an
// unparseable selector, a failed id draw and a CAS error are all otherwise
// silent in production — only the send path logs for itself. A standing
// subscription that never fires and never says why is the worst failure this
// feature has.
//
// The error carries store and selector diagnostics, never the message body (the
// store's validation names fields, not values), so logging it is safe.
func (e *SubscriptionEvaluator) OnSessionState(ctx context.Context, sessionID string, to machine.State) error {
	class, ok := TriggerClassFor(to)
	if !ok {
		return nil
	}
	err := e.fire(ctx, sessionID, class)
	if err != nil {
		e.logger.Warn().Err(err).
			Str("session_id", sessionID).
			Str("class", string(class)).
			Msg("broadcast subscription: evaluating a session transition failed")
	}
	return err
}

// ReconcileAll is the safety net, run periodically off the worker tick. It
// expires overdue subscriptions, then re-checks every session that still carries
// a live one and fires those already sitting in a trigger state.
//
// Two things need it: a transition that happened while the daemon was down (no
// hook was listening), and the startup bulk orphan sweep, which writes states
// through a path the transition hook does not observe.
//
// Errors are accumulated and joined; one bad session never stops the sweep.
func (e *SubscriptionEvaluator) ReconcileAll(ctx context.Context) error {
	var errs []error
	if _, err := e.subs.ExpireOverdue(ctx, e.now()); err != nil {
		errs = append(errs, fmt.Errorf("expire overdue broadcast subscriptions: %w", err))
	}
	if e.sessions == nil {
		// Loud rather than inert: a sweep that cannot read session state silently
		// stops covering daemon-downtime transitions, which is exactly the failure
		// it exists to prevent.
		errs = append(errs, errors.New("broadcast subscription reconcile: no session state reader wired (see WithSessionStates)"))
		return errors.Join(errs...)
	}
	owners, err := e.subs.ListActiveOwnerSessionIDs(ctx)
	if err != nil {
		errs = append(errs, fmt.Errorf("list broadcast subscription owners: %w", err))
		return errors.Join(errs...)
	}
	for _, sessionID := range owners {
		session, err := e.sessions.Get(ctx, sessionID)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				// The watched session is gone. There is no foreign key, so nothing
				// cascaded the subscription away; expiry retires it. Not an error.
				continue
			}
			errs = append(errs, fmt.Errorf("read session %s for broadcast subscription reconcile: %w", sessionID, err))
			continue
		}
		class, ok := TriggerClassFor(session.State)
		if !ok {
			continue
		}
		if err := e.fire(ctx, sessionID, class); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// fire is the shared firing path for both the transition hook and the sweep.
//
// ORDERING IS THE CONTRACT: MarkFired (a CAS on state = 'active') runs BEFORE
// the send, and only a true return proceeds. That single ordering is what makes
// a concurrent double transition — or a transition racing the reconcile sweep —
// produce exactly one broadcast. The reverse order would send twice and mark
// once. Do not reorder it.
//
// Because MarkFired must record the broadcast id but the CAS precedes the send,
// the id is generated here, up front, and handed to BOTH the CAS and the sender.
func (e *SubscriptionEvaluator) fire(ctx context.Context, sessionID string, class Class) error {
	subs, err := e.subs.ListActiveForSession(ctx, sessionID)
	if err != nil {
		return fmt.Errorf("list active broadcast subscriptions for session %s: %w", sessionID, err)
	}
	now := e.now()
	var errs []error
	for i := range subs {
		sub := subs[i]
		if !class.Matches(sub.TriggerEvent) {
			continue
		}
		// The store already filters on expiry, but the sweep is lazy and this is
		// the last gate before a message goes out: a stale registration must never
		// fire, whichever store implementation is underneath.
		if !sub.ExpiresAt.After(now) {
			continue
		}
		// Parsed before the CAS on purpose: an unparseable selector is a bad row,
		// not a fired one, and burning the subscription on it would lose the
		// registration without delivering anything.
		selector, err := bcast.Parse(sub.Selector)
		if err != nil {
			errs = append(errs, fmt.Errorf("parse selector of broadcast subscription %s: %w", sub.ID, err))
			continue
		}
		broadcastID, err := sqlutil.NewID()
		if err != nil {
			errs = append(errs, fmt.Errorf("new broadcast id for subscription %s: %w", sub.ID, err))
			continue
		}
		won, err := e.subs.MarkFired(ctx, sub.ID, broadcastID, now)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				// Deleted underneath us between the list and the CAS. Benign.
				continue
			}
			errs = append(errs, fmt.Errorf("mark broadcast subscription %s fired: %w", sub.ID, err))
			continue
		}
		if !won {
			// Someone else already fired this one. Silence is correct: a lost CAS is
			// the mechanism working, not a problem to report.
			continue
		}
		originChatID := ""
		if sub.OriginChatID != nil {
			originChatID = *sub.OriginChatID
		}
		if err := e.sender.SendBroadcast(ctx, SubscriptionBroadcast{
			ID:             broadcastID,
			SubscriptionID: sub.ID,
			Selector:       selector,
			Message:        sub.Message,
			OriginChatID:   originChatID,
			ExpiresAt:      now.Add(FiredBroadcastExpiry),
		}); err != nil {
			// The subscription STAYS fired. The broadcast's own delivery worker owns
			// retry, and un-firing here would risk a duplicate fire on the next
			// transition — a second message is worse than a missed one for a
			// coordination signal. The log names the subscription and the broadcast,
			// never the body.
			e.logger.Warn().Err(err).
				Str("subscription_id", sub.ID).
				Str("broadcast_id", broadcastID).
				Str("session_id", sessionID).
				Msg("broadcast subscription: send failed; the subscription stays fired")
			errs = append(errs, fmt.Errorf("send broadcast for subscription %s: %w", sub.ID, err))
			continue
		}
		e.logger.Info().
			Str("subscription_id", sub.ID).
			Str("broadcast_id", broadcastID).
			Str("session_id", sessionID).
			Str("class", string(class)).
			Msg("broadcast subscription fired")
	}
	return errors.Join(errs...)
}
