load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "skillinstall",
    srcs = [
        "doc.go",
        "extract.go",
    ],
    importpath = "github.com/recurser/bossalib/skillinstall",
    visibility = ["//visibility:public"],
    deps = ["@com_github_gofrs_flock//:flock"],
)

go_test(
    name = "skillinstall_test",
    srcs = [
        "extract_test.go",
        "perms_unix_test.go",
    ],
    embed = [":skillinstall"],
)
