// Package plugin manages the lifecycle of external plugins using
// hashicorp/go-plugin. Plugins are discovered from configuration,
// launched as subprocesses communicating over gRPC, and health-checked
// on a regular interval.
package plugin

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"sync"
	"time"

	goplugin "github.com/hashicorp/go-plugin"
	"github.com/rs/zerolog"

	"github.com/recurser/bossalib/config"
	bossanovav1 "github.com/recurser/bossalib/gen/bossanova/v1"
	sharedplugin "github.com/recurser/bossalib/plugin"
	"github.com/recurser/bossalib/safego"
	"github.com/recurser/bossalib/vcs"
	"github.com/recurser/bossd/internal/claude"
	"github.com/recurser/bossd/internal/db"
	"github.com/recurser/bossd/internal/plugin/eventbus"
	"github.com/recurser/bossd/internal/status"
)

// notifyStatusChangeTimeout bounds each plugin's NotifyStatusChange RPC so a
// slow plugin can't leak goroutines when status changes fire frequently.
const notifyStatusChangeTimeout = 5 * time.Second

// healthCheckInterval is how often the host pings each plugin.
const healthCheckInterval = 30 * time.Second

// PluginStatus reports the runtime state of a single plugin.
type PluginStatus struct {
	Name      string
	Running   bool
	ID        string
	StartedAt time.Time
}

// managedPlugin tracks a single running plugin process.
type managedPlugin struct {
	cfg             config.PluginConfig
	client          *goplugin.Client
	taskSource      TaskSource      // cached dispensed interface, nil if not a task source
	workflowService WorkflowService // cached dispensed interface, nil if not a workflow service
	startedAt       time.Time
}

// Host manages the lifecycle of all configured plugins.
type Host struct {
	mu          sync.Mutex
	plugins     []managedPlugin
	eventBus    *eventbus.Bus
	hostService *HostServiceServer
	logger      zerolog.Logger
	cancel      context.CancelFunc
	wg          sync.WaitGroup
	// cookieValue is the per-startup magic-cookie secret, generated by
	// Start and used for every plugin client launched in this daemon run.
	cookieValue string
}

// hasEnabledPlugin reports whether any of the configs is marked Enabled.
func hasEnabledPlugin(cfgs []config.PluginConfig) bool {
	for _, c := range cfgs {
		if c.Enabled {
			return true
		}
	}
	return false
}

// generatePluginCookie returns a fresh 32-byte hex string for the per-startup
// magic cookie. It is called once per daemon startup (Host.Start).
func generatePluginCookie() (string, error) {
	var buf [32]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", fmt.Errorf("generate plugin cookie: %w", err)
	}
	return hex.EncodeToString(buf[:]), nil
}

// New creates a plugin host. The VCS provider is used to create a
// HostServiceServer that plugins can call back to via the broker.
// If provider is nil, plugins will not have access to host services.
// Call Start to launch plugins.
func New(eventBus *eventbus.Bus, provider vcs.Provider, logger zerolog.Logger) *Host {
	var hostService *HostServiceServer
	if provider != nil {
		hostService = NewHostServiceServer(provider)
	}
	return &Host{
		eventBus:    eventBus,
		hostService: hostService,
		logger:      logger.With().Str("component", "plugin-host").Logger(),
	}
}

// Start discovers and launches all enabled plugins from the given
// configuration. It also starts a background health-check goroutine.
func (h *Host) Start(ctx context.Context, cfgs []config.PluginConfig) error {
	h.mu.Lock()
	defer h.mu.Unlock()

	// Only validate host-service deps when there's at least one enabled
	// plugin that could actually call back. With no plugins running,
	// partially-wired hosts (e.g. unit tests) stay usable.
	if h.hostService != nil && hasEnabledPlugin(cfgs) {
		if err := h.hostService.Validate(); err != nil {
			return fmt.Errorf("plugin host: %w", err)
		}
	}

	cookie, err := generatePluginCookie()
	if err != nil {
		return err
	}
	h.cookieValue = cookie

	// Registering the same plugin twice gives each instance its own
	// in-memory state, so per-session dedup maps (e.g. repair's
	// `repairing` map) can't coordinate across instances and both will
	// spawn a chat for the same trigger. Drop duplicates loudly so the
	// misconfiguration is visible — main.go also dedupes settings.Plugins
	// on load, this is the last-line defense in case a different caller
	// hands us a duplicated slice.
	if deduped, dropped := config.DedupPluginConfigs(cfgs); dropped {
		h.logger.Warn().Int("before", len(cfgs)).Int("after", len(deduped)).Msg("dropping duplicate plugin entries in Start")
		cfgs = deduped
	}

	for _, cfg := range cfgs {
		if !cfg.Enabled {
			h.logger.Info().Str("plugin", cfg.Name).Msg("plugin disabled, skipping")
			continue
		}

		client := goplugin.NewClient(&goplugin.ClientConfig{
			HandshakeConfig:  NewHandshake(h.cookieValue),
			VersionedPlugins: NewVersionedPluginMap(h.hostService),
			Cmd:              exec.Command(cfg.Path),
			AllowedProtocols: []goplugin.Protocol{
				goplugin.ProtocolGRPC,
			},
			Logger: newHCLogAdapter(h.logger.With().Str("plugin", cfg.Name).Logger()),
		})

		// Start launches the subprocess and performs the handshake. A single
		// failing plugin is logged and skipped rather than aborting the host:
		// one broken binary on disk (e.g. a stale build after a schema change,
		// or a plugin that panics on startup) shouldn't DOS the daemon and
		// block every other plugin from loading. Validate() already enforces
		// the stricter "fail loud on unwired host deps" path before this loop.
		_, err := client.Client()
		if err != nil {
			client.Kill()
			h.logger.Error().
				Err(err).
				Str("plugin", cfg.Name).
				Str("path", cfg.Path).
				Msg("failed to start plugin; skipping and continuing with remaining plugins")
			continue
		}

		h.logger.Info().
			Str("plugin", cfg.Name).
			Str("path", cfg.Path).
			Str("id", client.ID()).
			Msg("plugin started")

		mp := managedPlugin{
			cfg:       cfg,
			client:    client,
			startedAt: time.Now(),
		}

		// Try to dispense each interface. Because all plugin types share
		// the same gRPC connection, Dispense succeeds even if the plugin
		// subprocess doesn't implement the service. We probe with GetInfo
		// to verify the service is actually registered before caching.
		rpcClient, err := client.Client()
		if err == nil {
			raw, err := rpcClient.Dispense(sharedplugin.PluginTypeTaskSource)
			if err == nil {
				if ts, ok := raw.(TaskSource); ok {
					if _, probeErr := ts.GetInfo(context.Background()); probeErr == nil {
						mp.taskSource = ts
						h.logger.Info().Str("plugin", cfg.Name).Msg("dispensed TaskSource interface")
					}
				}
			}

			// Try to dispense the WorkflowService interface.
			raw, err = rpcClient.Dispense(sharedplugin.PluginTypeWorkflow)
			if err == nil {
				if ws, ok := raw.(WorkflowService); ok {
					if _, probeErr := ws.GetInfo(context.Background()); probeErr == nil {
						mp.workflowService = ws
						h.logger.Info().Str("plugin", cfg.Name).Msg("dispensed WorkflowService interface")
					}
				}
			}
		}

		h.plugins = append(h.plugins, mp)
	}

	// Start health-check loop.
	hctx, cancel := context.WithCancel(ctx)
	h.cancel = cancel
	h.wg.Go(func() {
		h.healthCheckLoop(hctx)
	})

	h.logger.Info().Int("count", len(h.plugins)).Msg("plugin host started")
	return nil
}

// Stop gracefully kills all plugin processes and stops health checking.
// Stop is idempotent.
func (h *Host) Stop() error {
	h.mu.Lock()
	defer h.mu.Unlock()

	if h.cancel != nil {
		h.cancel()
		h.cancel = nil
	}

	// Wait for health-check goroutine to exit before killing plugins,
	// so we don't race on the plugins slice.
	h.mu.Unlock()
	h.wg.Wait()
	h.mu.Lock()

	for i := range h.plugins {
		client := h.plugins[i].client
		pid := 0
		if rc := client.ReattachConfig(); rc != nil {
			pid = rc.Pid
		}
		killWithTimeout(h.logger, h.plugins[i].cfg.Name, client.Kill, pid, killTimeout)
		h.logger.Info().Str("plugin", h.plugins[i].cfg.Name).Msg("plugin stopped")
	}
	h.plugins = nil

	h.logger.Info().Msg("plugin host stopped")
	return nil
}

// killTimeout bounds how long Stop waits for a single plugin to shut down.
// go-plugin's own Kill already does graceful-close → 2s wait → SIGKILL, but
// it then blocks on an internal waitgroup that can stall indefinitely if a
// log-pump goroutine leaks. 3s gives go-plugin's graceful path a full chance
// to run before we fall through to the direct OS-level SIGKILL fallback.
const killTimeout = 3 * time.Second

// killWithTimeout runs kill in a panic-recovered goroutine and bounds the
// wait. If kill does not return within timeout, we SIGKILL pid directly so
// daemon shutdown cannot hang on a stuck subprocess. Any goroutine still
// running inside go-plugin's Kill is left to drain on its own — closing the
// subprocess's pipes causes it to finish shortly after. Factored into a
// func(kill, pid) signature so the timeout path is testable without a real
// go-plugin subprocess.
func killWithTimeout(logger zerolog.Logger, name string, kill func(), pid int, timeout time.Duration) {
	done := safego.Go(logger, kill)
	select {
	case <-done:
		return
	case <-time.After(timeout):
		logger.Warn().
			Str("plugin", name).
			Dur("timeout", timeout).
			Int("pid", pid).
			Msg("plugin Kill timed out; force-killing via SIGKILL")
		if pid > 0 {
			if proc, err := os.FindProcess(pid); err == nil {
				_ = proc.Kill()
			}
		}
	}
}

// Plugins returns the current status of all managed plugins.
func (h *Host) Plugins() []PluginStatus {
	h.mu.Lock()
	defer h.mu.Unlock()

	statuses := make([]PluginStatus, len(h.plugins))
	for i, p := range h.plugins {
		statuses[i] = PluginStatus{
			Name:      p.cfg.Name,
			Running:   !p.client.Exited(),
			ID:        p.client.ID(),
			StartedAt: p.startedAt,
		}
	}
	return statuses
}

// GetTaskSources returns the cached TaskSource interfaces for all plugins
// that implement it. The interfaces are dispensed once at startup and
// reused for each poll cycle.
func (h *Host) GetTaskSources() []TaskSource {
	h.mu.Lock()
	defer h.mu.Unlock()

	var sources []TaskSource
	for _, p := range h.plugins {
		if p.taskSource != nil {
			sources = append(sources, p.taskSource)
		}
	}
	return sources
}

// SetWorkflowDeps injects workflow and attempt dependencies into the host
// service so that plugins can create/manage workflows and Claude attempts.
func (h *Host) SetWorkflowDeps(store db.WorkflowStore, sessions db.SessionStore, chats db.ClaudeChatStore, runner claude.ClaudeRunner) {
	if h.hostService != nil {
		h.hostService.SetWorkflowDeps(store, sessions, chats, runner)
	}
}

// SetSessionDeps injects the dependencies needed for session-related RPCs.
func (h *Host) SetSessionDeps(repos db.RepoStore, sessions db.SessionStore, tracker *status.PRTracker, chatTracker *status.Tracker) {
	if h.hostService != nil {
		h.hostService.SetSessionDeps(repos, sessions, tracker, chatTracker)
	}
}

// NotifyStatusChange broadcasts a PR status change to all workflow plugins.
// Each plugin call runs in its own panic-recovered goroutine with a bounded
// timeout so a slow plugin cannot hold a goroutine open indefinitely.
func (h *Host) NotifyStatusChange(ctx context.Context, sessionID string, displayStatus vcs.PRDisplayStatus, hasFailures bool) {
	services := h.GetWorkflowServices()
	pbStatus := bossanovav1.PRDisplayStatus(displayStatus)
	for _, svc := range services {
		s := svc
		safego.Go(h.logger, func() {
			cctx, cancel := context.WithTimeout(ctx, notifyStatusChangeTimeout)
			defer cancel()
			if err := s.NotifyStatusChange(cctx, sessionID, pbStatus, hasFailures); err != nil {
				h.logger.Warn().Err(err).Str("session_id", sessionID).Msg("failed to notify plugin of status change")
			}
		})
	}
}

// GetWorkflowServices returns the cached WorkflowService interfaces for all
// plugins that implement it. The interfaces are dispensed once at startup
// and reused.
func (h *Host) GetWorkflowServices() []WorkflowService {
	h.mu.Lock()
	defer h.mu.Unlock()

	var services []WorkflowService
	for _, p := range h.plugins {
		if p.workflowService != nil {
			services = append(services, p.workflowService)
		}
	}
	return services
}

// healthCheckLoop periodically pings each plugin and logs failures.
func (h *Host) healthCheckLoop(ctx context.Context) {
	ticker := time.NewTicker(healthCheckInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			h.pingAll()
		}
	}
}

// pingTimeout bounds each individual plugin ping. go-plugin's Ping() has no
// context, so we race it against a timer in a goroutine — a hung ping can't
// block the health-check loop or shutdown (see Stop below, which waits on h.wg).
const pingTimeout = 5 * time.Second

// pingAll checks each plugin's health.
//
// Snapshots the plugin list under h.mu, then releases the lock before issuing
// any RPC. Holding h.mu across a blocking Ping would deadlock shutdown because
// Stop also takes h.mu, so a hung plugin would wedge the whole daemon.
func (h *Host) pingAll() {
	h.mu.Lock()
	snapshot := make([]managedPlugin, len(h.plugins))
	copy(snapshot, h.plugins)
	h.mu.Unlock()

	for _, p := range snapshot {
		if p.client.Exited() {
			h.logger.Warn().Str("plugin", p.cfg.Name).Msg("plugin process exited")
			continue
		}

		rpcClient, err := p.client.Client()
		if err != nil {
			h.logger.Warn().Err(err).Str("plugin", p.cfg.Name).Msg("health check: failed to get client")
			continue
		}

		// Race Ping against a timer. A hung Ping leaks one goroutine per
		// cycle, but the health-check loop keeps running and Stop doesn't block.
		done := make(chan error, 1)
		safego.Go(h.logger, func() {
			done <- rpcClient.Ping()
		})
		select {
		case err := <-done:
			if err != nil {
				h.logger.Warn().Err(err).Str("plugin", p.cfg.Name).Msg("health check: ping failed")
			}
		case <-time.After(pingTimeout):
			h.logger.Warn().Str("plugin", p.cfg.Name).Dur("timeout", pingTimeout).Msg("health check: ping timed out")
		}
	}
}
