load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "telemetry",
    srcs = [
        "client.go",
        "events.go",
        "interceptor.go",
    ],
    importpath = "github.com/recurser/bossalib/telemetry",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/bossalib/config",
        "@com_connectrpc_connect//:connect",
        "@com_github_posthog_posthog_go//:posthog-go",
        "@com_github_rs_zerolog//log",
    ],
)

go_test(
    name = "telemetry_test",
    srcs = [
        "client_test.go",
        "events_test.go",
        "interceptor_test.go",
    ],
    data = [
        "events.go",
        "//docs/analytics:events.md",
        "//services/web/src/analytics:events.ts",
    ],
    embed = [":telemetry"],
    rundir = ".",
    deps = [
        "//lib/bossalib/config",
        "@com_connectrpc_connect//:connect",
        "@com_github_posthog_posthog_go//:posthog-go",
        "@com_github_rs_zerolog//:zerolog",
        "@com_github_rs_zerolog//log",
    ],
)
