load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "credmaterialize",
    srcs = [
        "ambientauth.go",
        "credmaterialize.go",
        "hardlinks_other.go",
        "hardlinks_unix.go",
        "hardlinks_windows.go",
        "keyedmutex.go",
        "merge.go",
        "openflags_other.go",
        "openflags_unix.go",
    ],
    importpath = "github.com/recurser/bossd/internal/credmaterialize",
    visibility = ["//services/bossd:__subpackages__"],
    deps = [
        "//lib/bossalib/config",
        "@com_github_rs_zerolog//:zerolog",
    ],
)

go_test(
    name = "credmaterialize_test",
    srcs = [
        "ambientauth_test.go",
        "credmaterialize_test.go",
    ],
    embed = [":credmaterialize"],
    deps = ["@com_github_rs_zerolog//:zerolog"],
)
