load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "eventbus",
    srcs = ["eventbus.go"],
    importpath = "github.com/recurser/bossd/internal/plugin/eventbus",
    visibility = ["//services/bossd:__subpackages__"],
    deps = [
        "//lib/bossalib/gen/bossanova/v1:bossanova",
        "@com_github_rs_zerolog//:zerolog",
    ],
)

go_test(
    name = "eventbus_test",
    srcs = ["eventbus_test.go"],
    embed = [":eventbus"],
    deps = [
        "//lib/bossalib/gen/bossanova/v1:bossanova",
        "@com_github_rs_zerolog//:zerolog",
    ],
)
