load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "daemonstate",
    srcs = ["state.go"],
    importpath = "github.com/recurser/bossalib/daemonstate",
    visibility = ["//visibility:public"],
)

go_test(
    name = "daemonstate_test",
    srcs = ["state_test.go"],
    embed = [":daemonstate"],
)
