package main

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/recurser/boss/cmd/skillgen"
)

// TestSkillMatchesGenerated asserts that the committed skill payload — the
// routing index inside SKILL.md's markers *and* every generated
// references/<group>.md — byte-equals a fresh render of the real CLI tree.
// This makes `make test` fail on any drift: a command or flag added without
// running `make gen-skill`, a hand-edited reference file, a reference the
// generator no longer emits, or one it emits that was never committed.
func TestSkillMatchesGenerated(t *testing.T) {
	bundle, err := skillgen.Generate(rootCmd())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	skill := readSkillContent(t)
	want, err := skillgen.Inject(skill, bundle.Index)
	if err != nil {
		t.Fatalf("Inject: %v", err)
	}
	if want != skill {
		t.Errorf("SKILL.md is stale — run `make gen-skill`.\n" +
			"The generated command reference index no longer matches the CLI.")
	}

	refDir := filepath.Join(skillDir(t), "references")
	entries, err := os.ReadDir(refDir)
	if err != nil {
		t.Fatalf("read %s: %v", refDir, err)
	}
	onDisk := map[string]string{}
	for _, e := range entries {
		if e.IsDir() {
			t.Errorf("%s contains an unexpected directory %q — run `make gen-skill`", refDir, e.Name())
			continue
		}
		data, err := os.ReadFile(filepath.Join(refDir, e.Name()))
		if err != nil {
			t.Fatalf("read %s: %v", e.Name(), err)
		}
		onDisk["references/"+e.Name()] = string(data)
	}

	for _, key := range sortedKeys(bundle.References) {
		got, ok := onDisk[key]
		if !ok {
			t.Errorf("%s is missing — run `make gen-skill`", key)
			continue
		}
		if got != bundle.References[key] {
			t.Errorf("%s is stale — run `make gen-skill`.\n"+
				"Its bytes no longer match the generated CLI reference.", key)
		}
	}
	for _, key := range sortedKeys(onDisk) {
		if _, ok := bundle.References[key]; !ok {
			t.Errorf("%s is not generated by any command group — run `make gen-skill` to prune it", key)
		}
	}
}

// TestGeneratedReferencesRenderEveryExtractedCommand is the content-preservation
// oracle for the per-group CLI reference split.
//
// The oracle is the DOC MODEL, not another renderer. TestSkillMatchesGenerated
// above compares the generator's output against the same generator, so a renderer
// that silently dropped every Long, alias, flag or example would still pass after
// a regeneration. Here the expectations come from skillgen.Extract — the
// []clidoc.GroupDoc the renderer cannot influence — and the observations come from
// the rendered references. It never needs regenerating: both sides derive from the
// live CLI at test time, so it cannot rot into vacuity.
//
// It runs in package main because skillgen cannot import cmd; only main can build
// the real rootCmd(), so this runs against the live group/command tree rather than
// a fixture.
//
// Every extracted command is checked against BOTH renderings of its group:
//
//   - the freshly generated bundle, which catches an in-memory renderer mutation
//     (e.g. renderCommand skipping c.Long) even while the committed markdown on
//     disk still carries the prose; and
//   - the committed references/<id>.md bytes, which catches a hand-edit deleting a
//     command block from the payload agents actually read.
//
// Byte equality between the two is deliberately not asserted here — that is
// TestSkillMatchesGenerated's job.
func TestGeneratedReferencesRenderEveryExtractedCommand(t *testing.T) {
	groups, err := skillgen.Extract(rootCmd())
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if len(groups) == 0 {
		t.Fatalf("Extract returned no groups — the oracle would be vacuous")
	}

	bundle, err := skillgen.Generate(rootCmd())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	refDir := filepath.Join(skillDir(t), "references")

	for _, g := range groups {
		key := "references/" + g.ID + ".md"

		rendered, ok := bundle.References[key]
		if !ok {
			t.Errorf("group %q: Generate emitted no %s — every group with commands needs exactly one reference", g.ID, key)
			continue
		}
		committed, err := os.ReadFile(filepath.Join(refDir, g.ID+".md"))
		if err != nil {
			t.Errorf("group %q: read committed %s: %v", g.ID, key, err)
			continue
		}
		if len(g.Commands) == 0 {
			t.Errorf("group %q: Extract returned an empty group — it should have been skipped", g.ID)
			continue
		}

		for _, source := range []struct {
			label string
			body  string
		}{
			{"freshly generated " + key, rendered},
			{"committed " + key, string(committed)},
		} {
			for _, c := range g.Commands {
				heading := "### `" + c.UsageLine + "`"
				assertRefContains(t, source.label, g.ID, c.Path, source.body, heading, "command heading")

				// Scope every remaining assertion to this command's OWN section.
				// Checking against the whole group body would let a fragment that
				// merely occurs under a sibling command satisfy the assertion:
				// flags like --json or --repo recur across a group, so dropping
				// one command's flag list would otherwise still pass.
				section, ok := commandSection(source.body, heading)
				if !ok {
					continue // the heading assertion above already reported it
				}
				if c.Synopsis != "" {
					assertRefContains(t, source.label, g.ID, c.Path, section, c.Synopsis, "synopsis")
				}
				if c.Long != "" {
					assertRefContains(t, source.label, g.ID, c.Path, section, c.Long, "long description")
				}
				for _, alias := range c.Aliases {
					// Assert the RENDERED form, not the bare alias. A cobra alias
					// replaces the leaf name, so it must appear parent-scoped
					// ("boss plugin ls", not "boss ls") — and a bare "ls" occurs
					// incidentally throughout these files, so asserting it would
					// stay green even if the alias loop were deleted outright.
					assertRefContains(t, source.label, g.ID, c.Path, section,
						"Alias: `"+parentPath(c.Path)+" "+alias+"`", "alias")
				}
				for _, f := range c.Flags {
					assertRefContains(t, source.label, g.ID, c.Path, section, "`--"+f.Name+"`", "flag name")
					if f.Usage != "" {
						assertRefContains(t, source.label, g.ID, c.Path, section, f.Usage, "usage of flag --"+f.Name)
					}
				}
				for _, ex := range c.Examples {
					assertRefContains(t, source.label, g.ID, c.Path, section, ex.Command, "example command")
				}
			}
		}
	}

	if len(bundle.References) != len(groups) {
		t.Errorf("Generate emitted %d reference files for %d extracted groups — want exactly one per group",
			len(bundle.References), len(groups))
	}
}

// commandSection returns the slice of a rendered group body belonging to one
// command: from its "### `…`" heading up to the next command heading (or the end
// of the group). Within a group body "### " starts a command heading and nothing
// else, so splitting on it is exact.
//
// Scoping the oracle's assertions to a single command is what stops a fragment
// shared across the group (a recurring flag name, a duplicated usage string)
// from satisfying an assertion for a command whose own rendering lost it.
func commandSection(body, heading string) (string, bool) {
	start := strings.Index(body, heading)
	if start < 0 {
		return "", false
	}
	rest := body[start+len(heading):]
	if end := strings.Index(rest, "\n### "); end >= 0 {
		return heading + rest[:end], true
	}
	return heading + rest, true
}

// parentPath drops a command path's leaf, mirroring how renderCommand scopes an
// alias. It is re-derived here on purpose: the oracle must not share a helper
// with the renderer it is auditing.
func parentPath(path string) string {
	if i := strings.LastIndex(path, " "); i >= 0 {
		return path[:i]
	}
	return path
}

// assertRefContains reports a dropped fragment naming the group id, the command
// path and which rendering lost it, so a falsification transcript identifies the
// exact command rather than just reporting "content missing".
func assertRefContains(t *testing.T, source, groupID, cmdPath, body, want, what string) {
	t.Helper()
	if strings.Contains(body, want) {
		return
	}
	t.Errorf("group %q, command %q: %s is missing from the %s\n  wanted to find: %q",
		groupID, cmdPath, what, source, want)
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// skillDir returns the canonical boss skill source directory, walking up from
// this test file's location to locate the repo root. This avoids depending on
// `make copy-skills` having populated mirror copies before `go test` compiles
// the test binary.
func skillDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("runtime.Caller failed")
	}
	dir := filepath.Dir(thisFile)
	for {
		candidate := filepath.Join(dir, "services", "boss", "internal", "skillinstall", "skills", "boss")
		if _, err := os.Stat(filepath.Join(candidate, "SKILL.md")); err == nil {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("could not locate services/boss/internal/skillinstall/skills/boss/SKILL.md walking up from %s", filepath.Dir(thisFile))
		}
		dir = parent
	}
}

// readSkillContent reads the canonical boss SKILL.md.
func readSkillContent(t *testing.T) string {
	t.Helper()
	path := filepath.Join(skillDir(t), "SKILL.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
