load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "chatdelivery",
    srcs = ["chatdelivery.go"],
    importpath = "github.com/recurser/bossalib/chatdelivery",
    visibility = ["//visibility:public"],
)

go_test(
    name = "chatdelivery_test",
    srcs = ["chatdelivery_test.go"],
    embed = [":chatdelivery"],
)
