// Section-scoped prose gate for the boss-review skill (BOS-742 task 2).
//
// Task 1 landed skills-toolbox/bs-review-triage.mjs — a deterministic helper that
// dedupes reviewer findings on (file, line, title) and promotes a group to
// must-fix on severity OR cross-reviewer convergence. This test pins the SKILL.md
// / core-methodology.md prose that wires Phase 5/6 to that helper, and pins the
// Phase 0 ledger template's `evidence:` field added alongside it.
//
// The assertions are SECTION-SCOPED: each slices the relevant heading-to-heading
// range with sliceSection, then asserts inside the slice. A whole-file
// assert.match would pass on a sentence anywhere in the document — including one
// this ticket did not touch — which is exactly the name-exact ratchet failure
// mode BOS-742 exists to prevent.
//
// Node built-ins only — cron worktrees are dependency-free.

import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

const rootDir = fileURLToPath(new URL('..', import.meta.url))

// BOS-271 collapsed the published cores onto the boss-repair single-source
// topology: the canonical committed home is the embedded skillinstall payload.
// The plugins/bossd-plugin-claude mirror is generated by `make copy-skills` and
// must stay byte-identical, so both are asserted here.
const REVIEW_MIRRORS = [
  'services/boss/internal/skillinstall/skills/boss-review',
  'plugins/bossd-plugin-claude/skilldata/skills/boss-review',
]

const read = (relPath) => readFileSync(path.join(rootDir, relPath), 'utf8')

/**
 * Slice `text` from the first occurrence of `startMarker` to the first
 * occurrence of `endMarker` found after it. Both markers MUST be found — a -1
 * index fails loudly (via assert) rather than silently slicing the whole file
 * or returning an empty string.
 */
function sliceSection(text, startMarker, endMarker) {
  const start = text.indexOf(startMarker)
  assert.notEqual(start, -1, `missing section start marker: ${JSON.stringify(startMarker)}`)
  const from = start + startMarker.length
  const end = text.indexOf(endMarker, from)
  assert.notEqual(
    end,
    -1,
    `missing section end marker after ${JSON.stringify(startMarker)}: ${JSON.stringify(endMarker)}`,
  )
  return text.slice(from, end)
}

for (const mirror of REVIEW_MIRRORS) {
  const skill = read(`${mirror}/SKILL.md`)
  const coreMethodology = read(`${mirror}/references/core-methodology.md`)

  const phase5 = sliceSection(skill, '## Phase 5', '## Phase 6')
  const phase6 = sliceSection(skill, '## Phase 6', '## Phase 7')
  const phase7 = sliceSection(skill, '## Phase 7', '## Phase 8')
  const phase0 = sliceSection(skill, '## Phase 0', '## Phase 1')
  const findingsContract = sliceSection(skill, '## Findings contract', '## Acceptance-criteria')
  const coreFindingsContract = sliceSection(
    coreMethodology,
    '## Findings contract',
    '## Severity policy',
  )
  const convergenceLoop = sliceSection(coreMethodology, '## Convergence loop', '### Oscillation')
  const severityPolicy = sliceSection(coreMethodology, '## Severity policy', '## Always-on rounds')

  test(`[${mirror}] findings contract documents patch field and exact repo-root anchor rule`, () => {
    for (const section of [findingsContract, coreFindingsContract]) {
      assert.match(section, /"patch":\s*\{\s*"file":\s*"<repo-root-relative\s+path>"/)
      assert.match(section, /`file`\s+is\s+rooted\s+at\s+the\s+repository\s+root/)
      assert.match(section, /`old_string`\s+must\s+match\s+exactly\s+once/)
      assert.match(
        section,
        /rejects\s+rather\s+than\s+guesses\s+on\s+zero\s+or\s+multiple\s+matches/,
      )
      assert.match(section, /"patch": null[\s\S]{0,120}`patchReason`/)
    }
  })

  test(`[${mirror}] Phase 5 calls the triage helper's categorize verb and applies the coverage override to its pool`, () => {
    assert.match(phase5, /bs-review-triage\.mjs["'`]?\s+categorize/)
    // Clause-scoped, not token-scoped: this section already said "coverage
    // override" and "pool" BEFORE this ticket, so matching either token alone
    // would gate nothing. Pin the sentence that actually ties the override to
    // the helper's returned `pool`.
    assert.match(phase5, /Apply\s+that\s+override\s+over\s+the\s+returned\s+`pool`/)
  })

  test(`[${mirror}] Phase 5 passes compact file-backed triage inputs instead of the full lens payload`, () => {
    // A large diff can make LENSES_JSON exceed execve's argv limit. The helper needs
    // only indexed `skill` values, so Phase 0 persists that compact mapping and
    // Phase 5 passes its path rather than the complete matched-file payload.
    assert.match(phase0, /lenses\.map\(\(\{ skill \}\) => \(\{ skill \}\)\)/)
    assert.match(phase5, /--lens-entries-file\s+"\$RUN_TMP\/lens-entries\.json"/)
    assert.doesNotMatch(phase5, /categorize[^\n]*\$LENSES_JSON/)
  })

  test(`[${mirror}] Phase 5 treats a selected fallback reviewer with no output as unread`, () => {
    assert.match(phase0, /expected-reviewer-outputs\.json/)
    assert.match(phase5, /--expected-outputs-file/)
    assert.match(
      phase5,
      /run\s+is\s+unread\s+only\s+when\s+it\s+never\s+produces\s+the\s+reviewer\s+output\s+that\s+was\s+ultimately\s+required/,
    )
  })

  test(`[${mirror}] Phase 5 distinguishes an unread findings file from a malformed item`, () => {
    // The helper's `categorize` verb reports a whole findings file it could not
    // read as an array, not just malformed items. Prose that lumps the two
    // together tells the operator to under-react to a reviewer whose entire
    // output went unread, so the distinction is pinned here.
    assert.match(phase5, /could\s+not\s+read\s+as\s+a\s+list\s+of\s+findings/)
    assert.match(phase5, /entire\s+output\s+went\s+unread/)
    assert.match(phase5, /not\s+partial\s+ones/)
    // A round whose reviewers' files never parsed yields zero must-fix. The
    // clean-exit rule must not read that as a clean round.
    assert.match(phase5, /no\s+`invalid`\s+entry\s+is\s+still\s+unrepaired/)
    assert.match(phase5, /Every\s+unrepaired\s+`invalid` entry\s+blocks\s+a\s+clean\s+verdict/)
  })

  test(`[${mirror}] Phase 5 says patch rejections stay invalid but route to the narrative remainder`, () => {
    assert.match(
      phase5,
      /malformed,\s+missing-file,\s+non-unique,\s+or\s+conflict-composed\s+`patch`/,
    )
    assert.match(
      phase5,
      /route\s+the\s+underlying\s+finding\s+through\s+the\s+narrative\s+must-fix\s+path/,
    )
  })

  test(`[${mirror}] Phase 5 qualifies convergence promotion on distinct reviewers`, () => {
    assert.match(phase5, /convergence/i)
    assert.match(phase5, /distinct\s+reviewers/i)
    // A rule worded merely "occurrences" would license same-lens double
    // counting (the same reviewer reporting the same finding twice). The
    // prose must tie the count to reviewers, never raw occurrences.
    assert.match(phase5, /never\s+occurrences/i)
  })

  test(`[${mirror}] Phase 6 adjudicates before fixing and requires evidence on a verified disposition`, () => {
    assert.match(phase6, /adjudicate\s+before\s+you\s+fix/i)
    assert.match(phase6, /confirmed\s+or\s+falsified/i)
    assert.match(phase6, /\bverified\b/)
    // A bare /evidence/ matched this section BEFORE this ticket ("never
    // clobbers a prior round's evidence"), so it gates nothing. Pin the clause
    // that binds the evidence to the `verified` disposition itself.
    assert.match(phase6, /the\s+`evidence`\s+that\s+settled\s+it/)
  })

  test(`[${mirror}] Phase 6 applies patchable findings mechanically before narrative fix dispatch`, () => {
    assert.match(phase6, /Partition\s+the\s+must-fix\s+items\s+into\s+patchable\s+and\s+narrative/)
    assert.match(phase6, /Apply\s+patchable\s+findings\s+mechanically\s+in\s+the\s+orchestrator/)
    assert.match(
      phase6,
      /compose\s+overlapping\s+patches\s+in\s+one\s+file\s+into\s+the\s+helper's\s+single\s+exact\s+replacement/,
    )
    assert.match(
      phase6,
      /re-read\s+the\s+current\s+file\s+bytes\s+immediately\s+before\s+each\s+application/,
    )
    assert.match(
      phase6,
      /Dispatch\s+a\s+fresh\s+`general-purpose`\s+fix\s+subagent\s+\(awaited\)\s+\*\*only\*\*/,
    )
  })

  test(`[${mirror}] core-methodology convergence loop carries the same mechanical patch path`, () => {
    assert.match(
      convergenceLoop,
      /Partition\s+must-fix\s+items\s+into\s+patchable\s+and\s+narrative/,
    )
    assert.match(
      convergenceLoop,
      /Apply\s+patchable\s+findings\s+mechanically\s+in\s+the\s+orchestrator/,
    )
    assert.match(
      convergenceLoop,
      /Dispatch\s+a\s+fix\s+step\s+\*\*only\*\*\s+for\s+the\s+narrative\s+remainder/,
    )
  })

  test(`[${mirror}] Phase 7 report schema carries the patch summary tally`, () => {
    assert.match(
      phase7,
      /"patchSummary":\s*\{\s*"patchable":\s*P,\s*"narrative":\s*N,\s*"nullWithReason":\s*R\s*\}/,
    )
    assert.match(phase7, /patchable\/narrative\/null-with-reason\s+tally/)
  })

  // BOS-798: `proseWrap: preserve` means prettier does not reflow prose, so a hand-split or
  // worker-inserted sentence leaves an orphan line mid-paragraph that `--check` calls correctly
  // formatted. The formatter cannot be the orchestrator's only markdown check, so Phase 6 must
  // say when the eyeball happens. The fix subagent commits its own work inside the dispatch, so
  // the timing has two halves and both are pinned: the subagent's brief carries the pre-commit
  // eyeball, and the orchestrator amends on return. A pin on "before the commit" alone would
  // freeze a timing this flow cannot reach.
  // Pins are `\s+`-tolerant: this paragraph rewraps whenever a neighbouring sentence is edited.
  test(`[${mirror}] Phase 6 eyeballs a returned markdown hunk and routes the pre-commit half to the subagent`, () => {
    assert.match(phase6, /returned\s+diff\s+touches\s+markdown/)
    assert.match(phase6, /the\s+moment\s+the\s+dispatch\s+returns/)
    assert.match(phase6, /delegating\s+the\s+edit\s+does\s+not\s+delegate\s+this/)
    // The timing must name the subagent's own commit, or the rule prescribes a moment that has
    // already passed by the time the orchestrator sees the hunk.
    assert.match(phase6, /subagent\s+commits\s+its\s+own\s+work/)
    assert.match(phase6, /put\s+the\s+eyeball\s+in\s+its\s+brief\s+too/)
    assert.match(phase6, /check\s+the\s+hunk\s+before\s+you\s+commit/)
    assert.match(phase6, /on\s+return\s+amend\s+its\s+commit/)
    // The orchestrator's half must stay reachable: the subagent may have committed more than
    // once, so an amend-only instruction is unperformable whenever its work is not the tip.
    assert.match(phase6, /add\s+a\s+follow-up\s+one\s+when\s+it\s+is\s+no\s+longer\s+the\s+tip/)
    // The *reason* must be resident, not just the instruction: a rule whose rationale is missing
    // is the first one dropped when the round is behind.
    assert.match(phase6, /`proseWrap: preserve`\s+does\s+not\s+reflow\s+prose/)
    assert.match(
      phase6,
      /orphan\s+line\s+mid-paragraph\s+that\s+`--check`\s+reports\s+as\s+correctly\s+formatted/,
    )
    // The table-cell half of the rule.
    assert.match(
      phase6,
      /run\s+the\s+formatter\s+immediately\s+after\s+editing\s+a\s+markdown\s+table\s+cell/,
    )
    assert.match(phase6, /churn\s+is\s+padding-only/)
  })

  test(`[${mirror}] Phase 6 hands '## Leave as-is' to the confirming round`, () => {
    // `## Leave as-is` and "confirming round" both appeared here pre-ticket;
    // the handoff sentence that joins them is the load-bearing addition.
    assert.match(
      phase6,
      /Feed\s+the\s+confirming\s+round\s+the\s+ledger's\s+`## Leave\s+as-is`\s+entries/,
    )
    assert.match(phase6, /factually\s+false/i)
    assert.match(phase6, /re-opens\s+the\s+finding/i)
  })

  test(`[${mirror}] confirming rounds rebuild their indexed lens identity map`, () => {
    assert.match(phase5, /fresh\s+`LENSES_JSON`/)
    assert.match(phase5, /full\s+confirming\s+surface/)
    assert.match(
      phase5,
      /union\s+of\s+newly\s+changed\s+files\s+and\s+the\s+cited\s+files\s+of\s+every\s+verified\s+finding/,
    )
    assert.match(phase5, /\$RUN_TMP\/round<N>\/lens-entries\.json/)
    assert.match(phase5, /Do\s+not\s+reuse\s+the\s+initial-round\s+mapping/)
  })

  test(`[${mirror}] Phase 6 cannot finish clean with malformed reviewer findings`, () => {
    assert.match(phase6, /zero\s+must-fix\s+\*\*and\s+zero\s+unrepaired\s+`invalid` entries\*\*/)
    assert.match(phase6, /report `capped`, never `clean`/)
  })

  test(`[${mirror}] invalid-only rounds repair their owning reviewer before dispatching a fixer`, () => {
    assert.match(
      phase5,
      /repair\s+every\s+unrepaired `invalid` entry\s+through\s+its\s+owning\s+reviewer/,
    )
    assert.match(phase5, /same\s+round's\s+original\s+review\s+surface/)
    assert.match(
      phase5,
      /Do \*\*not\*\* dispatch\s+the\s+Phase\s+6\s+fixer\s+with\s+an\s+empty\s+must-fix\s+list/,
    )
    assert.match(phase5, /same\s+cap\s+and\s+ledger\s+history/)
  })

  test(`[${mirror}] Phase 7 makes malformed payloads and verification evidence durable`, () => {
    const phase7 = sliceSection(skill, '## Phase 7', '## Phase 8')
    // Every space is `\s+`: prettier rewraps this prose at 100 columns, so a
    // literal space here would make the gate fail on a reflow rather than on a
    // dropped guarantee. Both halves are asserted — the payload AND the source
    // that names whose output it was — because retaining one without the other
    // leaves invalid evidence that cannot be routed back to a reviewer.
    assert.match(phase7, /retained\s+reviewer\/output\s+source,\s+and\s+malformed\s+payload/)
    assert.match(
      phase7,
      /\"evidence\": \"<file:line[ ]read[ ]or[ ]command[ ]result[ ]that[ ]settled[ ]it>\"/,
    )
    assert.match(phase7, /including\s+each\s+verified\s+finding's\s+evidence/)
  })

  test(`[${mirror}] the Phase 0 ledger template's Leave as-is comment carries rationale: and evidence:`, () => {
    const leaveAsIsTemplate = sliceSection(phase0, '## Leave as-is', '```')
    assert.match(leaveAsIsTemplate, /rationale:/)
    assert.match(leaveAsIsTemplate, /evidence:/)
  })

  test(`[${mirror}] core-methodology.md's severity policy states convergence promotion on distinct reviewers`, () => {
    assert.match(severityPolicy, /convergence\s+promotion/i)
    assert.match(severityPolicy, /distinct\s+reviewers/i)
  })

  test(`[${mirror}] the added Phase 5/6 and severity-policy prose stays project-agnostic`, () => {
    const forbidden = /bossanova|linear|BOS-\d+/i
    assert.doesNotMatch(phase5, forbidden)
    assert.doesNotMatch(phase6, forbidden)
    assert.doesNotMatch(severityPolicy, forbidden)
  })
}

test('repo-local boss-review extensions restate patch for prose-class findings', () => {
  const rels = [
    '.claude/skills/boss-review-ce/SKILL.md',
    '.claude/skills/boss-review-crossmodel/SKILL.md',
    '.claude/skills/boss-review-golang/SKILL.md',
    '.claude/skills/boss-review-thermonuclear/SKILL.md',
    '.claude/skills/boss-review-tui/SKILL.md',
    '.claude/skills/boss-review-web/SKILL.md',
    '.claude/skills/thermonuclear-review/SKILL.md',
  ]
  for (const rel of rels) {
    const text = read(rel)
    assert.match(text, /"patch"/, `${rel} must name the patch field`)
    assert.match(text, /prose-class\s+findings/, `${rel} must name prose-class findings`)
    assert.match(text, /patchReason/, `${rel} must name the null-with-reason hatch`)
  }
})

// BOS-814 review P1: the repo-local `boss-review-ce` round extension keys its inline fallback on
// whether a CE review pass ACTUALLY RAN, not on whether the skill loaded. Keying it on absence
// alone fails open: `ce-code-review` can load and still perform no review — its nested reviewer
// dispatch can fail from this already-subagent-hosted round, or it can return skipped/empty
// output. Normalized into an `ok: true` envelope with empty `items[]`, that is indistinguishable
// from a clean round, so the core suppresses its own Tier 2/3 review and an unperformed pass
// silently retires the whole code-review round.
//
// Dual-mirrored: .claude is the source, .codex is regenerated by `make codex-skills`. Assert both
// so a hand-edit of one mirror, or a stale codex sync, trips the gate.
const REVIEW_CE_EXTENSION_DIRS = ['.claude/skills/boss-review-ce', '.codex/skills/boss-review-ce']

for (const skillDir of REVIEW_CE_EXTENSION_DIRS) {
  test(`[${skillDir}] the inline fallback covers dispatch failure and skipped CE, not just absence`, () => {
    // Scoped to the rubric section, not the whole file, so unrelated prose cannot satisfy these.
    // sliceSection is not usable here: it requires a following marker, and this is the last
    // section of the document.
    const raw = read(`${skillDir}/SKILL.md`)
    const start = raw.indexOf('## Inline fallback rubric')
    assert.notStrictEqual(
      start,
      -1,
      `${skillDir}/SKILL.md must keep the "## Inline fallback rubric" section`,
    )
    const nextHeading = raw.indexOf('\n## ', start + 1)
    const rubric = (nextHeading === -1 ? raw.slice(start) : raw.slice(start, nextHeading)).replace(
      /\s+/g,
      ' ',
    )

    // Each trigger is asserted on its own. A single "unavailable" match would pass on the
    // absence-only wording this test exists to forbid.
    for (const [label, pattern] of [
      ['skill unavailable on this harness', /unavailable\s+on\s+this\s+harness/i],
      [
        'nested reviewer dispatch cannot run or errors',
        /dispatch\s+cannot\s+run|dispatch\s+errors/i,
      ],
      ['CE returns skipped/empty/unparseable output', /skipped, empty, or\s+unparseable/i],
    ]) {
      assert.match(rubric, pattern, `${skillDir}/SKILL.md must route "${label}" to the inline pass`)
    }

    // And it must say why an empty envelope cannot stand in for an unperformed pass — without
    // this, a reader can still normalize a skipped CE result into a clean-looking round.
    assert.match(
      rubric,
      /suppresses\s+its\s+own\s+Tier\s+2\/3\s+review/i,
      `${skillDir}/SKILL.md must state that an empty envelope suppresses the core's own Tier 2/3 review`,
    )
  })

  // BOS-814: the fallback above makes an undispatchable CE round SAFE, not FUNCTIONAL. CE never
  // reviews inline — `ce-code-review` Stage 4 spawns one sub-agent per persona and its verification
  // gate spawns one validator per finding — so an `allowed-tools` without a dispatch primitive means
  // the CE path can never run at all. The round would degrade to the inline rubric on every single
  // invocation while every gate stayed green: a feature that is inert by construction, with
  // acceptance criterion (c) ("ce-code-review findings appear in the Boss report contract")
  // unsatisfiable in practice. Pin the primitive, not just the fallback.
  test(`[${skillDir}] frontmatter grants the dispatch primitive CE needs to spawn reviewers`, () => {
    const raw = read(`${skillDir}/SKILL.md`)
    // Scope to the frontmatter block. A whole-file match would pass on any prose mentioning Task.
    const fm = raw.match(/^---\n([\s\S]*?)\n---/)
    assert.ok(fm, `${skillDir}/SKILL.md must open with a YAML frontmatter block`)
    const allowed = fm[1].match(/^allowed-tools:\s*(.+)$/m)
    assert.ok(allowed, `${skillDir}/SKILL.md frontmatter must declare allowed-tools`)
    const tools = allowed[1].split(',').map((t) => t.trim())
    assert.ok(
      tools.includes('Task'),
      `${skillDir}/SKILL.md must grant Task in allowed-tools (got: ${tools.join(', ')}) — ce-code-review dispatches its persona reviewers as sub-agents, so without it the CE round is undispatchable and silently inert`,
    )
    assert.ok(
      tools.includes('Skill'),
      `${skillDir}/SKILL.md must keep Skill in allowed-tools — it loads compound-engineering:ce-code-review`,
    )
    // The grant is dispatch-only. Read-only must stay read-only, so the write primitives CE's
    // interactive mode would use must NOT leak in alongside it.
    for (const forbidden of ['Write', 'Edit', 'NotebookEdit']) {
      assert.ok(
        !tools.includes(forbidden),
        `${skillDir}/SKILL.md must NOT grant ${forbidden} — this round is read-only and must not mutate the worktree`,
      )
    }
    // And the reason must be written down, so a later reader does not "tidy away" the grant as
    // over-broad for a read-only round.
    // Flatten first: prettier wraps this prose at 100 columns, so any literal space in the pattern
    // is a line break waiting to happen.
    const flat = raw.replace(/\s+/g, ' ')
    assert.match(
      flat,
      /why\s+`Task`\s+is\s+in\s+this\s+extension's\s+`allowed-tools`/i,
      `${skillDir}/SKILL.md must explain why a read-only round carries Task`,
    )
    assert.match(
      flat,
      /inert\s+while\s+its\s+gates\s+stay\s+green/i,
      `${skillDir}/SKILL.md must name the inert-but-green failure mode withholding Task would cause`,
    )
  })

  // BOS-814 review P2: the extension advertises `plan:<path>` on the CE invocation, but nothing
  // hands it one — `boss-build` Step 6c invokes `boss-review` with no arguments and the core's
  // round envelope carries only mergeBase/head/changedFiles/runTmp/outPath. Without a deterministic
  // recovery rule the round silently drops CE's requirements-completeness pass on every build run,
  // while acceptance criteria were available all along. Pin the recovery rule, not just the arg.
  test(`[${skillDir}] the CE round can resolve plan:<path> without an envelope field`, () => {
    const raw = read(`${skillDir}/SKILL.md`)
    // Flatten: prettier wraps this prose at 100 columns, so a literal space in the pattern is a
    // line break waiting to happen.
    const flat = raw.replace(/\s+/g, ' ')
    for (const [label, pattern] of [
      [
        'the discovery command over the reviewed range',
        /git\s+diff\s+--name-only\s+--diff-filter=A[^`]*docs\/plans\/\*\.md/,
      ],
      ['the exactly-one match requirement', /resolves\s+to\s+\*\*exactly\s+one\*\*\s+file/i],
      ['the omit-rather-than-guess rule', /omit\s+`plan:`\s+entirely[\s\S]{0,120}never\s+guess/i],
    ]) {
      assert.match(
        flat,
        pattern,
        `${skillDir}/SKILL.md must state ${label} so the CE round recovers the plan path itself`,
      )
    }
  })
}
