// Section-scoped prose gate for the boss-review skill (BOS-742 task 2).
//
// Task 1 landed skills-toolbox/bs-review-triage.mjs — a deterministic helper that
// dedupes reviewer findings on (file, line, title) and promotes a group to
// must-fix on severity OR cross-reviewer convergence. This test pins the SKILL.md
// / core-methodology.md prose that wires Phase 5/6 to that helper, and pins the
// Phase 0 ledger template's `evidence:` field added alongside it.
//
// The assertions are SECTION-SCOPED: each slices the relevant heading-to-heading
// range with sliceSection, then asserts inside the slice. A whole-file
// assert.match would pass on a sentence anywhere in the document — including one
// this ticket did not touch — which is exactly the name-exact ratchet failure
// mode BOS-742 exists to prevent.
//
// Node built-ins only — cron worktrees are dependency-free.

import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

const rootDir = fileURLToPath(new URL('..', import.meta.url))

// BOS-271 collapsed the published cores onto the boss-repair single-source
// topology: the canonical committed home is the embedded skillinstall payload.
// The plugins/bossd-plugin-claude mirror is generated by `make copy-skills` and
// must stay byte-identical, so both are asserted here.
const REVIEW_MIRRORS = [
  'services/boss/internal/skillinstall/skills/boss-review',
  'plugins/bossd-plugin-claude/skilldata/skills/boss-review',
]

const read = (relPath) => readFileSync(path.join(rootDir, relPath), 'utf8')

/**
 * Slice `text` from the first occurrence of `startMarker` to the first
 * occurrence of `endMarker` found after it. Both markers MUST be found — a -1
 * index fails loudly (via assert) rather than silently slicing the whole file
 * or returning an empty string.
 */
function sliceSection(text, startMarker, endMarker) {
  const start = text.indexOf(startMarker)
  assert.notEqual(start, -1, `missing section start marker: ${JSON.stringify(startMarker)}`)
  const from = start + startMarker.length
  const end = text.indexOf(endMarker, from)
  assert.notEqual(
    end,
    -1,
    `missing section end marker after ${JSON.stringify(startMarker)}: ${JSON.stringify(endMarker)}`,
  )
  return text.slice(from, end)
}

for (const mirror of REVIEW_MIRRORS) {
  const skill = read(`${mirror}/SKILL.md`)
  const coreMethodology = read(`${mirror}/references/core-methodology.md`)

  const phase5 = sliceSection(skill, '## Phase 5', '## Phase 6')
  const phase6 = sliceSection(skill, '## Phase 6', '## Phase 7')
  const phase0 = sliceSection(skill, '## Phase 0', '## Phase 1')
  const severityPolicy = sliceSection(coreMethodology, '## Severity policy', '## Always-on rounds')

  test(`[${mirror}] Phase 5 calls the triage helper's categorize verb and applies the coverage override to its pool`, () => {
    assert.match(phase5, /bs-review-triage\.mjs["'`]?\s+categorize/)
    // Clause-scoped, not token-scoped: this section already said "coverage
    // override" and "pool" BEFORE this ticket, so matching either token alone
    // would gate nothing. Pin the sentence that actually ties the override to
    // the helper's returned `pool`.
    assert.match(phase5, /Apply that override over the returned\s+`pool`/)
  })

  test(`[${mirror}] Phase 5 passes compact file-backed triage inputs instead of the full lens payload`, () => {
    // A large diff can make LENSES_JSON exceed execve's argv limit. The helper needs
    // only indexed `skill` values, so Phase 0 persists that compact mapping and
    // Phase 5 passes its path rather than the complete matched-file payload.
    assert.match(phase0, /lenses\.map\(\(\{ skill \}\) => \(\{ skill \}\)\)/)
    assert.match(phase5, /--lens-entries-file\s+"\$RUN_TMP\/lens-entries\.json"/)
    assert.doesNotMatch(phase5, /categorize[^\n]*\$LENSES_JSON/)
  })

  test(`[${mirror}] Phase 5 treats a selected fallback reviewer with no output as unread`, () => {
    assert.match(phase0, /expected-reviewer-outputs\.json/)
    assert.match(phase5, /--expected-outputs-file/)
    assert.match(
      phase5,
      /run is unread only when it never produces the\s+reviewer output that was ultimately required/,
    )
  })

  test(`[${mirror}] Phase 5 distinguishes an unread findings file from a malformed item`, () => {
    // The helper's `categorize` verb reports a whole findings file it could not
    // read as an array, not just malformed items. Prose that lumps the two
    // together tells the operator to under-react to a reviewer whose entire
    // output went unread, so the distinction is pinned here.
    assert.match(phase5, /could not read as a list of findings/)
    assert.match(phase5, /entire\s+output went\s+unread/)
    assert.match(phase5, /not\s+partial ones/)
    // A round whose reviewers' files never parsed yields zero must-fix. The
    // clean-exit rule must not read that as a clean round.
    assert.match(phase5, /no\s+`invalid`\s+entry is still unrepaired/)
    assert.match(phase5, /Every\s+unrepaired\s+`invalid` entry blocks a clean verdict/)
  })

  test(`[${mirror}] Phase 5 qualifies convergence promotion on distinct reviewers`, () => {
    assert.match(phase5, /convergence/i)
    assert.match(phase5, /distinct reviewers/i)
    // A rule worded merely "occurrences" would license same-lens double
    // counting (the same reviewer reporting the same finding twice). The
    // prose must tie the count to reviewers, never raw occurrences.
    assert.match(phase5, /never occurrences/i)
  })

  test(`[${mirror}] Phase 6 adjudicates before fixing and requires evidence on a verified disposition`, () => {
    assert.match(phase6, /adjudicate before you fix/i)
    assert.match(phase6, /confirmed or falsified/i)
    assert.match(phase6, /\bverified\b/)
    // A bare /evidence/ matched this section BEFORE this ticket ("never
    // clobbers a prior round's evidence"), so it gates nothing. Pin the clause
    // that binds the evidence to the `verified` disposition itself.
    assert.match(phase6, /the\s+`evidence`\s+that settled it/)
  })

  test(`[${mirror}] Phase 6 hands '## Leave as-is' to the confirming round`, () => {
    // `## Leave as-is` and "confirming round" both appeared here pre-ticket;
    // the handoff sentence that joins them is the load-bearing addition.
    assert.match(phase6, /Feed the confirming round the ledger's\s+`## Leave as-is`\s+entries/)
    assert.match(phase6, /factually false/i)
    assert.match(phase6, /re-opens the finding/i)
  })

  test(`[${mirror}] confirming rounds rebuild their indexed lens identity map`, () => {
    assert.match(phase5, /fresh\s+`LENSES_JSON`/)
    assert.match(phase5, /full confirming surface/)
    assert.match(
      phase5,
      /union of newly changed files and the cited files of every verified finding/,
    )
    assert.match(phase5, /\$RUN_TMP\/round<N>\/lens-entries\.json/)
    assert.match(phase5, /Do not reuse the\s+initial-round mapping/)
  })

  test(`[${mirror}] Phase 6 cannot finish clean with malformed reviewer findings`, () => {
    assert.match(phase6, /zero must-fix\s+\*\*and zero unrepaired\s+`invalid` entries\*\*/)
    assert.match(phase6, /report `capped`, never `clean`/)
  })

  test(`[${mirror}] invalid-only rounds repair their owning reviewer before dispatching a fixer`, () => {
    assert.match(phase5, /repair every unrepaired `invalid` entry through its owning\s+reviewer/)
    assert.match(phase5, /same round's original review surface/)
    assert.match(phase5, /Do \*\*not\*\* dispatch\s+the Phase 6 fixer with an empty must-fix list/)
    assert.match(phase5, /same cap and ledger history/)
  })

  test(`[${mirror}] Phase 7 makes malformed payloads and verification evidence durable`, () => {
    const phase7 = sliceSection(skill, '## Phase 7', '## Phase 8')
    // Every space is `\s+`: prettier rewraps this prose at 100 columns, so a
    // literal space here would make the gate fail on a reflow rather than on a
    // dropped guarantee. Both halves are asserted — the payload AND the source
    // that names whose output it was — because retaining one without the other
    // leaves invalid evidence that cannot be routed back to a reviewer.
    assert.match(phase7, /retained\s+reviewer\/output\s+source,\s+and\s+malformed\s+payload/)
    assert.match(phase7, /\"evidence\": \"<file:line read or command result that settled it>\"/)
    assert.match(phase7, /including each verified finding's evidence/)
  })

  test(`[${mirror}] the Phase 0 ledger template's Leave as-is comment carries rationale: and evidence:`, () => {
    const leaveAsIsTemplate = sliceSection(phase0, '## Leave as-is', '```')
    assert.match(leaveAsIsTemplate, /rationale:/)
    assert.match(leaveAsIsTemplate, /evidence:/)
  })

  test(`[${mirror}] core-methodology.md's severity policy states convergence promotion on distinct reviewers`, () => {
    assert.match(severityPolicy, /convergence promotion/i)
    assert.match(severityPolicy, /distinct reviewers/i)
  })

  test(`[${mirror}] the added Phase 5/6 and severity-policy prose stays project-agnostic`, () => {
    const forbidden = /bossanova|linear|BOS-\d+/i
    assert.doesNotMatch(phase5, forbidden)
    assert.doesNotMatch(phase6, forbidden)
    assert.doesNotMatch(severityPolicy, forbidden)
  })
}

// BOS-814 review P1: the repo-local `boss-review-ce` round extension keys its inline fallback on
// whether a CE review pass ACTUALLY RAN, not on whether the skill loaded. Keying it on absence
// alone fails open: `ce-code-review` can load and still perform no review — its nested reviewer
// dispatch can fail from this already-subagent-hosted round, or it can return skipped/empty
// output. Normalized into an `ok: true` envelope with empty `items[]`, that is indistinguishable
// from a clean round, so the core suppresses its own Tier 2/3 review and an unperformed pass
// silently retires the whole code-review round.
//
// Dual-mirrored: .claude is the source, .codex is regenerated by `make codex-skills`. Assert both
// so a hand-edit of one mirror, or a stale codex sync, trips the gate.
const REVIEW_CE_EXTENSION_DIRS = ['.claude/skills/boss-review-ce', '.codex/skills/boss-review-ce']

for (const skillDir of REVIEW_CE_EXTENSION_DIRS) {
  test(`[${skillDir}] the inline fallback covers dispatch failure and skipped CE, not just absence`, () => {
    // Scoped to the rubric section, not the whole file, so unrelated prose cannot satisfy these.
    // sliceSection is not usable here: it requires a following marker, and this is the last
    // section of the document.
    const raw = read(`${skillDir}/SKILL.md`)
    const start = raw.indexOf('## Inline fallback rubric')
    assert.notStrictEqual(
      start,
      -1,
      `${skillDir}/SKILL.md must keep the "## Inline fallback rubric" section`,
    )
    const nextHeading = raw.indexOf('\n## ', start + 1)
    const rubric = (nextHeading === -1 ? raw.slice(start) : raw.slice(start, nextHeading)).replace(
      /\s+/g,
      ' ',
    )

    // Each trigger is asserted on its own. A single "unavailable" match would pass on the
    // absence-only wording this test exists to forbid.
    for (const [label, pattern] of [
      ['skill unavailable on this harness', /unavailable on this harness/i],
      ['nested reviewer dispatch cannot run or errors', /dispatch cannot run|dispatch errors/i],
      ['CE returns skipped/empty/unparseable output', /skipped, empty, or unparseable/i],
    ]) {
      assert.match(rubric, pattern, `${skillDir}/SKILL.md must route "${label}" to the inline pass`)
    }

    // And it must say why an empty envelope cannot stand in for an unperformed pass — without
    // this, a reader can still normalize a skipped CE result into a clean-looking round.
    assert.match(
      rubric,
      /suppresses its own Tier 2\/3 review/i,
      `${skillDir}/SKILL.md must state that an empty envelope suppresses the core's own Tier 2/3 review`,
    )
  })

  // BOS-814: the fallback above makes an undispatchable CE round SAFE, not FUNCTIONAL. CE never
  // reviews inline — `ce-code-review` Stage 4 spawns one sub-agent per persona and its verification
  // gate spawns one validator per finding — so an `allowed-tools` without a dispatch primitive means
  // the CE path can never run at all. The round would degrade to the inline rubric on every single
  // invocation while every gate stayed green: a feature that is inert by construction, with
  // acceptance criterion (c) ("ce-code-review findings appear in the Boss report contract")
  // unsatisfiable in practice. Pin the primitive, not just the fallback.
  test(`[${skillDir}] frontmatter grants the dispatch primitive CE needs to spawn reviewers`, () => {
    const raw = read(`${skillDir}/SKILL.md`)
    // Scope to the frontmatter block. A whole-file match would pass on any prose mentioning Task.
    const fm = raw.match(/^---\n([\s\S]*?)\n---/)
    assert.ok(fm, `${skillDir}/SKILL.md must open with a YAML frontmatter block`)
    const allowed = fm[1].match(/^allowed-tools:\s*(.+)$/m)
    assert.ok(allowed, `${skillDir}/SKILL.md frontmatter must declare allowed-tools`)
    const tools = allowed[1].split(',').map((t) => t.trim())
    assert.ok(
      tools.includes('Task'),
      `${skillDir}/SKILL.md must grant Task in allowed-tools (got: ${tools.join(', ')}) — ce-code-review dispatches its persona reviewers as sub-agents, so without it the CE round is undispatchable and silently inert`,
    )
    assert.ok(
      tools.includes('Skill'),
      `${skillDir}/SKILL.md must keep Skill in allowed-tools — it loads compound-engineering:ce-code-review`,
    )
    // The grant is dispatch-only. Read-only must stay read-only, so the write primitives CE's
    // interactive mode would use must NOT leak in alongside it.
    for (const forbidden of ['Write', 'Edit', 'NotebookEdit']) {
      assert.ok(
        !tools.includes(forbidden),
        `${skillDir}/SKILL.md must NOT grant ${forbidden} — this round is read-only and must not mutate the worktree`,
      )
    }
    // And the reason must be written down, so a later reader does not "tidy away" the grant as
    // over-broad for a read-only round.
    // Flatten first: prettier wraps this prose at 100 columns, so any literal space in the pattern
    // is a line break waiting to happen.
    const flat = raw.replace(/\s+/g, ' ')
    assert.match(
      flat,
      /why\s+`Task`\s+is\s+in\s+this\s+extension's\s+`allowed-tools`/i,
      `${skillDir}/SKILL.md must explain why a read-only round carries Task`,
    )
    assert.match(
      flat,
      /inert\s+while\s+its\s+gates\s+stay\s+green/i,
      `${skillDir}/SKILL.md must name the inert-but-green failure mode withholding Task would cause`,
    )
  })

  // BOS-814 review P2: the extension advertises `plan:<path>` on the CE invocation, but nothing
  // hands it one — `boss-build` Step 6c invokes `boss-review` with no arguments and the core's
  // round envelope carries only mergeBase/head/changedFiles/runTmp/outPath. Without a deterministic
  // recovery rule the round silently drops CE's requirements-completeness pass on every build run,
  // while acceptance criteria were available all along. Pin the recovery rule, not just the arg.
  test(`[${skillDir}] the CE round can resolve plan:<path> without an envelope field`, () => {
    const raw = read(`${skillDir}/SKILL.md`)
    // Flatten: prettier wraps this prose at 100 columns, so a literal space in the pattern is a
    // line break waiting to happen.
    const flat = raw.replace(/\s+/g, ' ')
    for (const [label, pattern] of [
      [
        'the discovery command over the reviewed range',
        /git\s+diff\s+--name-only\s+--diff-filter=A[^`]*docs\/plans\/\*\.md/,
      ],
      ['the exactly-one match requirement', /resolves\s+to\s+\*\*exactly\s+one\*\*\s+file/i],
      ['the omit-rather-than-guess rule', /omit\s+`plan:`\s+entirely[\s\S]{0,120}never\s+guess/i],
    ]) {
      assert.match(
        flat,
        pattern,
        `${skillDir}/SKILL.md must state ${label} so the CE round recovers the plan path itself`,
      )
    }
  })
}
