import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

export const GENERATED_HEADER =
  '<!-- Generated by `make construct-skills` from SKILL.md.tmpl + construct.json. Do not edit directly. -->'

// Resolve the skills directory of the installed superpowers plugin. The component
// skills are read straight from the plugin cache at build time — nothing is vendored
// into this repo. `SUPERPOWERS_SKILLS_DIR` overrides for CI or non-standard installs.
export function resolveSkillsRoot(manifest, env = process.env) {
  if (env.SUPERPOWERS_SKILLS_DIR) return env.SUPERPOWERS_SKILLS_DIR
  return path.join(
    os.homedir(),
    '.claude/plugins/cache/claude-plugins-official/superpowers',
    manifest.superpowers_version,
    'skills',
  )
}

// True when the pinned superpowers skills are installed and readable. Generation
// requires this; the drift check degrades to a skip when it is false.
export function skillsRootAvailable(manifest, env = process.env) {
  return fs.existsSync(resolveSkillsRoot(manifest, env))
}

// Replace the body between <!-- INJECT:id --> and <!-- END INJECT:id --> (markers kept).
export function spliceInjection(template, id, body) {
  const open = `<!-- INJECT:${id} -->`
  const close = `<!-- END INJECT:${id} -->`
  const start = template.indexOf(open)
  const end = template.indexOf(close)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`construct: missing or malformed INJECT markers for "${id}"`)
  }
  return `${template.slice(0, start + open.length)}\n${body}\n${template.slice(end)}`
}

// Remove every span matching an excise regex (multiline). Throws if a pattern
// matches nothing — that means upstream text drifted and the strip is stale.
export function exciseSections(source, excisions = []) {
  let out = source
  for (const pattern of excisions) {
    if (!new RegExp(pattern, 'm').test(out)) {
      throw new Error(`construct: excise pattern matched nothing: ${pattern}`)
    }
    out = out.replace(new RegExp(pattern, 'gm'), '')
  }
  return out
}

// Apply [pattern, replacement] rewrites (relative skill links -> inlined refs).
export function applyRewrites(source, rewrites = []) {
  let out = source
  for (const [pattern, replacement] of rewrites) {
    out = out.replace(new RegExp(pattern, 'g'), replacement)
  }
  return out
}

function processInjection(vendorRoot, injection) {
  let body = fs.readFileSync(path.join(vendorRoot, injection.source), 'utf8')
  body = exciseSections(body, injection.excise)
  body = applyRewrites(body, injection.rewrite)
  return body.trim()
}

function formatMarkdown(markdown, { rootDir, filePath }) {
  try {
    return execFileSync('pnpm', ['exec', 'prettier', '--stdin-filepath', filePath], {
      cwd: rootDir,
      encoding: 'utf8',
      input: markdown,
      maxBuffer: 10 * 1024 * 1024,
    })
  } catch (error) {
    const detail = error.stderr || error.message
    throw new Error(`construct: failed to format ${filePath}: ${detail}`)
  }
}

function copyAsset(sourcePath, destPath) {
  const stat = fs.statSync(sourcePath)
  if (stat.isDirectory()) {
    fs.mkdirSync(destPath, { recursive: true })
    fs.chmodSync(destPath, stat.mode & 0o777)
    for (const entry of fs.readdirSync(sourcePath)) {
      copyAsset(path.join(sourcePath, entry), path.join(destPath, entry))
    }
    return
  }

  if (!stat.isFile()) return

  fs.mkdirSync(path.dirname(destPath), { recursive: true })
  fs.copyFileSync(sourcePath, destPath)
  fs.chmodSync(destPath, stat.mode & 0o777)
}

function assetMatches(sourcePath, destPath) {
  if (!fs.existsSync(destPath)) return false

  const sourceStat = fs.statSync(sourcePath)
  const destStat = fs.statSync(destPath)
  if (sourceStat.isDirectory()) {
    if (!destStat.isDirectory()) return false
    const sourceEntries = fs.readdirSync(sourcePath).sort()
    const destEntries = fs.readdirSync(destPath).sort()
    if (sourceEntries.length !== destEntries.length) return false
    for (let idx = 0; idx < sourceEntries.length; idx += 1) {
      if (sourceEntries[idx] !== destEntries[idx]) return false
      if (
        !assetMatches(
          path.join(sourcePath, sourceEntries[idx]),
          path.join(destPath, destEntries[idx]),
        )
      ) {
        return false
      }
    }
    return true
  }

  if (!sourceStat.isFile() || !destStat.isFile()) return false
  return (
    fs.readFileSync(sourcePath, 'utf8') === fs.readFileSync(destPath, 'utf8') &&
    (sourceStat.mode & 0o777) === (destStat.mode & 0o777)
  )
}

function processAssets(manifest, { rootDir, check }) {
  const vendorRoot = resolveSkillsRoot(manifest)
  let drift = false

  for (const asset of manifest.assets ?? []) {
    const sourcePath = path.join(vendorRoot, asset.source)
    const destPath = path.join(rootDir, asset.dest)

    if (check) {
      if (!assetMatches(sourcePath, destPath)) {
        drift = true
        console.error(`construct drift: ${asset.dest} is out of date — run "make construct-skills"`)
      }
      continue
    }

    copyAsset(sourcePath, destPath)
    console.log(`constructed ${asset.dest}`)
  }

  return drift
}

export function constructSkill(manifest, { rootDir }) {
  const vendorRoot = resolveSkillsRoot(manifest)
  let output = fs.readFileSync(path.join(rootDir, manifest.template), 'utf8')
  for (const injection of manifest.injections) {
    output = spliceInjection(output, injection.id, processInjection(vendorRoot, injection))
  }
  let constructed
  const fm = output.match(/^(---\n[\s\S]*?\n---\n)/)
  if (fm) {
    constructed = `${fm[1]}${GENERATED_HEADER}\n${output.slice(fm[1].length)}`
  } else {
    constructed = `${GENERATED_HEADER}\n${output}`
  }
  return formatMarkdown(constructed, { rootDir, filePath: path.join(rootDir, manifest.output) })
}

function loadManifests(rootDir) {
  const skillsDir = path.join(rootDir, '.claude', 'skills')
  const manifests = []
  for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const manifestPath = path.join(skillsDir, entry.name, 'construct.json')
    if (fs.existsSync(manifestPath)) {
      manifests.push(JSON.parse(fs.readFileSync(manifestPath, 'utf8')))
    }
  }
  return manifests
}

export function run({ rootDir, check }) {
  let drift = false
  for (const manifest of loadManifests(rootDir)) {
    if (!skillsRootAvailable(manifest)) {
      const where = resolveSkillsRoot(manifest)
      if (check) {
        // The component skills live in the plugin cache, not the repo. Where the
        // plugin is absent (a fresh CI runner, a public mirror), there is nothing
        // to check against — skip loudly rather than fail the whole suite.
        console.warn(
          `construct-skills-check skipped: superpowers ${manifest.superpowers_version} not found at ${where} (install the plugin or set SUPERPOWERS_SKILLS_DIR)`,
        )
        continue
      }
      throw new Error(
        `construct: superpowers ${manifest.superpowers_version} not found at ${where}. Install the superpowers plugin or set SUPERPOWERS_SKILLS_DIR.`,
      )
    }
    const constructed = constructSkill(manifest, { rootDir })
    const outPath = path.join(rootDir, manifest.output)
    if (check) {
      const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : ''
      if (current !== constructed) {
        drift = true
        console.error(
          `construct drift: ${manifest.output} is out of date — run "make construct-skills"`,
        )
      }
    } else {
      fs.writeFileSync(outPath, constructed)
      console.log(`constructed ${manifest.output}`)
    }
    drift = processAssets(manifest, { rootDir, check }) || drift
  }
  if (check && drift) process.exit(1)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2)
  const rootIdx = args.indexOf('--root')
  run({
    rootDir: rootIdx === -1 ? process.cwd() : args[rootIdx + 1],
    check: args.includes('--check'),
  })
}
