load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "upgrade",
    srcs = [
        "cache.go",
        "checker.go",
        "install.go",
        "token.go",
        "version.go",
    ],
    importpath = "github.com/recurser/boss/internal/upgrade",
    visibility = ["//services/boss:__subpackages__"],
    deps = [
        "//lib/bossalib/buildinfo",
        "//lib/bossalib/config",
        "@org_golang_x_mod//semver",
    ],
)

go_test(
    name = "upgrade_test",
    srcs = [
        "cache_perm_test.go",
        "checker_auth_test.go",
        "token_test.go",
        "upgrade_test.go",
    ],
    embed = [":upgrade"],
)
