#!/usr/bin/env bash
# check-boundary.sh — negative regression check for the plugin/host module
# boundary (BOS-344 Task 5).
#
# Bazel enforces the boundary with visibility: every host-internal package
# (services/bossd/internal/**, services/boss/internal/**, services/bosso/…)
# is generated by gazelle with `visibility = ["//services/<svc>:__subpackages__"]`.
# A plugin lives under //plugins/**, which is NOT a subpackage of any service,
# so a plugin target that depends on a host-internal label must fail to build
# at analysis time with a visibility error.
#
# This script proves that enforcement is live, not merely present: it seeds a
# forbidden dep into a plugin BUILD, asserts `bazel build` FAILS with a
# visibility violation, restores the file, then asserts the clean target builds.
# A build that succeeds with the seeded dep, or fails without it, is a boundary
# regression and exits non-zero.
#
# It mutates a real BUILD file in place and restores it from a backup via an
# EXIT trap, so an interrupted run never leaves the tree dirty.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

plugin_build="plugins/bossd-plugin-stub-runner/BUILD.bazel"
plugin_lib="//plugins/bossd-plugin-stub-runner:bossd-plugin-stub-runner_lib"
# A real host-internal label whose visibility is //services/bossd:__subpackages__.
forbidden_dep="//services/bossd/internal/db"

test -f "$plugin_build" || { echo "BOUNDARY_CHECK_FAIL: $plugin_build not found"; exit 1; }

backup="$(mktemp)"
cp "$plugin_build" "$backup"
restore() { cp "$backup" "$plugin_build"; rm -f "$backup"; }
trap restore EXIT

# 1. Clean tree must build (baseline sanity — the target is buildable to begin with).
if ! bazel build "$plugin_lib" >/dev/null 2>&1; then
  echo "BOUNDARY_CHECK_FAIL: clean build of $plugin_lib failed before seeding"
  exit 1
fi

# 2. Seed the forbidden dep into the go_library's deps list (first `deps = [`,
#    which belongs to the library target defined first in the file).
python3 - "$plugin_build" "$forbidden_dep" <<'PY'
import sys
path, dep = sys.argv[1], sys.argv[2]
with open(path) as f:
    lines = f.readlines()
out, injected = [], False
for line in lines:
    out.append(line)
    if not injected and line.strip() == "deps = [":
        out.append(f'        "{dep}",\n')
        injected = True
if not injected:
    sys.exit("BOUNDARY_CHECK_FAIL: no `deps = [` found to seed")
with open(path, "w") as f:
    f.writelines(out)
PY

# 3. Seeded build must FAIL with a visibility error.
seed_log="$(mktemp)"
if bazel build "$plugin_lib" >"$seed_log" 2>&1; then
  echo "BOUNDARY_CHECK_FAIL: seeded forbidden dep $forbidden_dep BUILT — boundary not enforced"
  cat "$seed_log"
  rm -f "$seed_log"
  exit 1
fi
if ! grep -qi "visibility" "$seed_log"; then
  echo "BOUNDARY_CHECK_FAIL: seeded build failed but not on a visibility error:"
  cat "$seed_log"
  rm -f "$seed_log"
  exit 1
fi
echo "OK: seeded plugin->host-internal dep failed the build with a visibility error"
rm -f "$seed_log"

# 4. Restore and confirm the clean target builds again (trap also restores).
restore
trap - EXIT
if ! bazel build "$plugin_lib" >/dev/null 2>&1; then
  echo "BOUNDARY_CHECK_FAIL: clean build of $plugin_lib failed after restore"
  exit 1
fi
echo "OK: clean tree builds after restore"
echo "BOUNDARY_CHECK_OK"
