package main

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	bossanovav1 "github.com/recurser/bossalib/gen/bossanova/v1"
	"github.com/rs/zerolog"
)

func TestGetChatTitle_FromJSONL(t *testing.T) {
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)

	worktree := "/Users/dave/Code/myproj"
	claudeID := "abcd-1234"

	projectKey := strings.NewReplacer("/", "-", ".", "-").Replace(worktree)
	projectDir := filepath.Join(tmpHome, ".claude", "projects", projectKey)
	if err := os.MkdirAll(projectDir, 0o700); err != nil {
		t.Fatal(err)
	}
	jsonl := `{"type":"user","message":{"role":"user","content":"Fix the bug in foo.go"}}` + "\n"
	if err := os.WriteFile(filepath.Join(projectDir, claudeID+".jsonl"), []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	srv := &Server{logger: zerolog.Nop()}
	resp, err := srv.GetChatTitle(context.Background(), &bossanovav1.GetChatTitleRequest{
		WorkDir: worktree, SessionId: claudeID,
	})
	if err != nil {
		t.Fatalf("GetChatTitle: %v", err)
	}
	if !resp.Supported {
		t.Error("Supported = false")
	}
	if resp.Title != "Fix the bug in foo.go" {
		t.Errorf("Title = %q, want %q", resp.Title, "Fix the bug in foo.go")
	}
	if resp.Explicit {
		t.Error("Explicit = true, want false for first user message")
	}
}

func TestGetChatTitle_SkipsMetaCaveatLeadingLine(t *testing.T) {
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)

	worktree := "/Users/dave/Code/myproj"
	claudeID := "abcd-caveat"

	projectKey := strings.NewReplacer("/", "-", ".", "-").Replace(worktree)
	projectDir := filepath.Join(tmpHome, ".claude", "projects", projectKey)
	if err := os.MkdirAll(projectDir, 0o700); err != nil {
		t.Fatal(err)
	}
	// Claude Code injects a synthetic caveat as the first type:"user" line,
	// flagged with top-level isMeta:true, when a session starts via a local
	// command. It must not become the title; the real user turn must win.
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"},"isMeta":true}`,
		`{"type":"user","message":{"role":"user","content":"Fix the bug in foo.go"}}`,
	}, "\n") + "\n"
	if err := os.WriteFile(filepath.Join(projectDir, claudeID+".jsonl"), []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	srv := &Server{logger: zerolog.Nop()}
	resp, err := srv.GetChatTitle(context.Background(), &bossanovav1.GetChatTitleRequest{
		WorkDir: worktree, SessionId: claudeID,
	})
	if err != nil {
		t.Fatalf("GetChatTitle: %v", err)
	}
	if resp.Title != "Fix the bug in foo.go" {
		t.Errorf("Title = %q, want the real user message", resp.Title)
	}
	if strings.Contains(resp.Title, "Caveat: The messages below") {
		t.Errorf("Title = %q, must not contain the caveat text", resp.Title)
	}
	if resp.Explicit {
		t.Error("Explicit = true, want false for first user message")
	}
}

func TestGetChatTitle_FromRenameSummary(t *testing.T) {
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)

	worktree := "/Users/dave/Code/myproj"
	claudeID := "abcd-rename"

	projectKey := strings.NewReplacer("/", "-", ".", "-").Replace(worktree)
	projectDir := filepath.Join(tmpHome, ".claude", "projects", projectKey)
	if err := os.MkdirAll(projectDir, 0o700); err != nil {
		t.Fatal(err)
	}
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"Initial prompt"}}`,
		`{"type":"summary","summary":"old name"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"ok"}}`,
		`{"type":"summary","summary":"the new name"}`,
	}, "\n") + "\n"
	if err := os.WriteFile(filepath.Join(projectDir, claudeID+".jsonl"), []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	srv := &Server{logger: zerolog.Nop()}
	resp, err := srv.GetChatTitle(context.Background(), &bossanovav1.GetChatTitleRequest{
		WorkDir: worktree, SessionId: claudeID,
	})
	if err != nil {
		t.Fatalf("GetChatTitle: %v", err)
	}
	if resp.Title != "the new name" {
		t.Errorf("Title = %q, want last summary", resp.Title)
	}
	if !resp.Explicit {
		t.Error("Explicit = false, want true for rename summary")
	}
}

func TestGetChatTitle_CustomTitles(t *testing.T) {
	tests := []struct {
		name     string
		claudeID string
		jsonl    []string
		want     string
	}{
		{
			name:     "from custom title",
			claudeID: "abcd-custom-title",
			jsonl: []string{
				`{"type":"custom-title","customTitle":"Rename Test","sessionId":"abcd-custom-title"}`,
				`{"type":"agent-name","agentName":"Rename Test","sessionId":"abcd-custom-title"}`,
				`{"type":"user","message":{"role":"user","content":"Initial prompt"}}`,
			},
			want: "Rename Test",
		},
		{
			name:     "custom title over summary",
			claudeID: "abcd-custom-over-summary",
			jsonl: []string{
				`{"type":"user","message":{"role":"user","content":"Initial prompt"}}`,
				`{"type":"summary","summary":"auto summary"}`,
				`{"type":"custom-title","customTitle":"User Title","sessionId":"abcd-custom-over-summary"}`,
			},
			want: "User Title",
		},
		{
			name:     "empty custom title falls back to summary",
			claudeID: "abcd-empty-custom-title",
			jsonl: []string{
				`{"type":"user","message":{"role":"user","content":"Initial prompt"}}`,
				`{"type":"custom-title","customTitle":"","sessionId":"abcd-empty-custom-title"}`,
				`{"type":"summary","summary":"rename summary"}`,
			},
			want: "rename summary",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpHome := t.TempDir()
			t.Setenv("HOME", tmpHome)

			worktree := "/Users/dave/Code/myproj"
			projectKey := strings.NewReplacer("/", "-", ".", "-").Replace(worktree)
			projectDir := filepath.Join(tmpHome, ".claude", "projects", projectKey)
			if err := os.MkdirAll(projectDir, 0o700); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(projectDir, tt.claudeID+".jsonl"), []byte(strings.Join(tt.jsonl, "\n")+"\n"), 0o600); err != nil {
				t.Fatal(err)
			}

			srv := &Server{logger: zerolog.Nop()}
			resp, err := srv.GetChatTitle(context.Background(), &bossanovav1.GetChatTitleRequest{
				WorkDir: worktree, SessionId: tt.claudeID,
			})
			if err != nil {
				t.Fatalf("GetChatTitle: %v", err)
			}
			if resp.Title != tt.want {
				t.Errorf("Title = %q, want %q", resp.Title, tt.want)
			}
			if !resp.Explicit {
				t.Error("Explicit = false, want true")
			}
		})
	}
}

func TestGetChatTitle_MissingFile(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	srv := &Server{logger: zerolog.Nop()}
	resp, err := srv.GetChatTitle(context.Background(), &bossanovav1.GetChatTitleRequest{
		WorkDir: "/nope", SessionId: "missing",
	})
	if err != nil {
		t.Fatalf("GetChatTitle should not error on missing file, got: %v", err)
	}
	if !resp.Supported {
		t.Error("Supported should be true even when title is empty")
	}
	if resp.Title != "" {
		t.Errorf("Title = %q, want empty", resp.Title)
	}
}

func TestLastTurnIsUserReadsRealTranscript(t *testing.T) {
	dir := t.TempDir()
	jsonl := `{"type":"user","message":{"role":"user","content":"hi"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"hello"}}` + "\n" +
		`{"type":"user","message":{"role":"user","content":"again"}}` + "\n"
	path := filepath.Join(dir, "abc.jsonl")
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	if !lastTurnIsUser(path) {
		t.Error("expected last turn to be user")
	}
}

func TestLastTurnIsUserReturnsFalseWhenAssistantLast(t *testing.T) {
	dir := t.TempDir()
	jsonl := `{"type":"user","message":{"role":"user","content":"hi"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"hello"}}` + "\n"
	path := filepath.Join(dir, "x.jsonl")
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}
	if lastTurnIsUser(path) {
		t.Error("expected false when assistant ends transcript")
	}
}

func TestLastTurnIsUserSkipsToolResultEntries(t *testing.T) {
	dir := t.TempDir()
	jsonl := `{"type":"user","message":{"role":"user","content":"hi"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"using tool"}}` + "\n" +
		`{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"ok"}]}}` + "\n"
	path := filepath.Join(dir, "x.jsonl")
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}
	if lastTurnIsUser(path) {
		t.Error("expected false when last user entry is tool_result-only")
	}
}

func TestTranscriptExistsReturnsTrueForRealFile(t *testing.T) {
	work := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home)

	key := pathToProjectKey(work)
	dir := filepath.Join(home, ".claude", "projects", key)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "sess.jsonl"), []byte("{}\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if !transcriptExists(work, "sess") {
		t.Error("expected transcriptExists=true")
	}
}

func TestTranscriptExistsReturnsFalseForMissing(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	if transcriptExists(t.TempDir(), "missing") {
		t.Error("expected transcriptExists=false")
	}
}

func TestPathToProjectKey(t *testing.T) {
	tests := []struct {
		name string
		path string
		want string
	}{
		// Regression (the "Session ID already in use" bug): Claude folds "_" to
		// "-" like every other non-alphanumeric char. Missing this made a
		// worktree ".../rlimit_nofile-..." key to ".../rlimit_nofile-..." while
		// Claude wrote ".../rlimit-nofile-...", so TranscriptExists missed the
		// file and the attach used --session-id (create) → collision.
		{name: "underscore folds to dash", path: "/Users/dave/wt/rlimit_nofile-dev", want: "-Users-dave-wt-rlimit-nofile-dev"},
		{name: "dotdir and separators", path: "/Users/dave/.wt/foo", want: "-Users-dave--wt-foo"},
		{name: "assorted non-alphanumerics", path: "/a/b_c d@e", want: "-a-b-c-d-e"},
		{name: "trailing slash cleaned", path: "/Users/dave/wt/", want: "-Users-dave-wt"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := pathToProjectKey(tt.path); got != tt.want {
				t.Errorf("pathToProjectKey(%q) = %q, want %q", tt.path, got, tt.want)
			}
		})
	}
}

// TestTranscriptExistsFindsUnderscoreWorktreeTranscript is the end-to-end
// regression for the reopen bug: the transcript is written at Claude's
// canonical key (which folds "_"→"-"), and transcriptExists — which derives its
// lookup path from pathToProjectKey — must still find it for a worktree path
// containing "_". The expected key is hard-coded so a regression in
// pathToProjectKey (dropping the "_" fold) makes this fail rather than silently
// agreeing with the fixture.
func TestTranscriptExistsFindsUnderscoreWorktreeTranscript(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	work := "/tmp/wt/bos-465-rlimit_nofile-dev"
	const claudeKey = "-tmp-wt-bos-465-rlimit-nofile-dev" // "_" folded to "-", as Claude writes it
	dir := filepath.Join(home, ".claude", "projects", claudeKey)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "sess.jsonl"), []byte("{}\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if !transcriptExists(work, "sess") {
		t.Error("expected transcriptExists=true for a worktree path containing '_'")
	}
}

func TestStripXMLTags(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{"plain text", "hello world", "hello world"},
		{"empty", "", ""},
		{"single tag pair", "<thinking>plan</thinking>", "plan"},
		{"surrounding whitespace trimmed", "  <tag>x</tag>  ", "x"},
		{"self-closing tag", "before<br/>after", "beforeafter"},
		{"lone open tag", "<command-name>", ""},
		{"tag with attributes", `<a href="x">link</a>`, "link"},
		{"less-than not a tag", "a < b and c > d", "a < b and c > d"},
		{"unclosed angle bracket kept", "<unclosed", "<unclosed"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := stripXMLTags(tt.in); got != tt.want {
				t.Errorf("stripXMLTags(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestFirstLine(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{"single line", "just one line", "just one line"},
		{"multi line keeps first", "first\nsecond\nthird", "first"},
		{"empty", "", ""},
		{"leading and trailing whitespace", "  padded  ", "padded"},
		{"leading newlines stripped", "\n\nfoo\nbar", "foo"},
		{"trailing newline", "solo\n", "solo"},
		{"whitespace before newline", "  line one  \n line two", "line one"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := firstLine(tt.in); got != tt.want {
				t.Errorf("firstLine(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestTruncate(t *testing.T) {
	atLimit := strings.Repeat("a", maxSummaryLen)
	overLimit := strings.Repeat("b", maxSummaryLen+5)
	tests := []struct {
		name string
		in   string
		want string
	}{
		{"short string unchanged", "short", "short"},
		{"empty unchanged", "", ""},
		{"exactly at limit unchanged", atLimit, atLimit},
		{"over limit truncated with ellipsis", overLimit, strings.Repeat("b", maxSummaryLen-3) + "..."},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := truncate(tt.in)
			if got != tt.want {
				t.Errorf("truncate(%q) = %q, want %q", tt.in, got, tt.want)
			}
			if len(got) > maxSummaryLen {
				t.Errorf("truncate output length %d exceeds maxSummaryLen %d", len(got), maxSummaryLen)
			}
		})
	}
}

func TestExtractText(t *testing.T) {
	tests := []struct {
		name string
		raw  string
		want string
	}{
		{"plain string content", `"Fix the bug"`, "Fix the bug"},
		{"empty raw", ``, ""},
		{"empty json string", `""`, ""},
		{"string strips xml and keeps first line", `"<thinking>x</thinking>do it\nignored"`, "xdo it"},
		{"array first text block", `[{"type":"text","text":"first block"},{"type":"text","text":"second"}]`, "first block"},
		{"array skips tool_result then text", `[{"type":"tool_result","text":"ignored"},{"type":"text","text":"real text"}]`, "real text"},
		{"array skips empty text block", `[{"type":"text","text":"   "},{"type":"text","text":"non-empty"}]`, "non-empty"},
		{"array all tool_result", `[{"type":"tool_result","text":"x"}]`, ""},
		{"invalid json", `{not json`, ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := extractText(json.RawMessage(tt.raw)); got != tt.want {
				t.Errorf("extractText(%s) = %q, want %q", tt.raw, got, tt.want)
			}
		})
	}
}

func TestHasUserTextBlock(t *testing.T) {
	tests := []struct {
		name string
		raw  string
		want bool
	}{
		{"non-empty string", `"hello"`, true},
		{"whitespace-only string", `"   "`, false},
		{"empty raw", ``, false},
		{"empty json string", `""`, false},
		{"array with text block", `[{"type":"text"}]`, true},
		{"array with text among tool_results", `[{"type":"tool_result"},{"type":"text"}]`, true},
		{"array of only tool_results", `[{"type":"tool_result"}]`, false},
		{"empty array", `[]`, false},
		{"invalid json", `{broken`, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hasUserTextBlock(json.RawMessage(tt.raw)); got != tt.want {
				t.Errorf("hasUserTextBlock(%s) = %v, want %v", tt.raw, got, tt.want)
			}
		})
	}
}

func TestParseSessionMeta_LastSummaryWins(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "session.jsonl")
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"First prompt"}}`,
		`{"type":"summary","summary":"first rename"}`,
		`{"type":"summary","summary":"second rename"}`,
	}, "\n") + "\n"
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, explicit := parseSessionMeta(path)
	if summary != "second rename" {
		t.Fatalf("summary = %q, want last summary", summary)
	}
	if !explicit {
		t.Fatal("explicit = false, want true")
	}
}

func TestParseSessionMeta_LargeLineDoesNotHideLaterSummary(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "session.jsonl")
	large := strings.Repeat("x", 300*1024)
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"First prompt"}}`,
		`{"type":"assistant","message":{"role":"assistant","content":"` + large + `"}}`,
		`{"type":"summary","summary":"later rename"}`,
	}, "\n") + "\n"
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, explicit := parseSessionMeta(path)
	if summary != "later rename" {
		t.Fatalf("summary = %q, want later rename", summary)
	}
	if !explicit {
		t.Fatal("explicit = false, want true")
	}
}

func TestParseSessionMeta_SummaryBeforeLongTailStillWins(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "session.jsonl")
	large := strings.Repeat("x", 300*1024)
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"First prompt"}}`,
		`{"type":"summary","summary":"old rename"}`,
		`{"type":"assistant","message":{"role":"assistant","content":"` + large + `"}}`,
	}, "\n") + "\n"
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, explicit := parseSessionMeta(path)
	if summary != "old rename" {
		t.Fatalf("summary = %q, want old rename", summary)
	}
	if !explicit {
		t.Fatal("explicit = false, want true")
	}
}

func TestParseSessionMeta_FirstMessageWhenNoSummary(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "session.jsonl")
	jsonl := `{"type":"user","message":{"role":"user","content":"First prompt"}}` + "\n"
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, explicit := parseSessionMeta(path)
	if summary != "First prompt" {
		t.Fatalf("summary = %q, want first user message", summary)
	}
	if explicit {
		t.Fatal("explicit = true, want false")
	}
}

func TestParseSessionMeta_SkipsMetaCaveatLine(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "session.jsonl")
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"},"isMeta":true}`,
		`{"type":"user","message":{"role":"user","content":"Real first message"}}`,
	}, "\n") + "\n"
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, explicit := parseSessionMeta(path)
	if summary != "Real first message" {
		t.Fatalf("summary = %q, want the real first message", summary)
	}
	if strings.Contains(summary, "Caveat: The messages below") {
		t.Fatalf("summary = %q, must not contain the caveat text", summary)
	}
	if explicit {
		t.Fatal("explicit = true, want false")
	}
}

func TestParseSessionMeta_AllMetaYieldsEmpty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "session.jsonl")
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"},"isMeta":true}`,
		`{"type":"user","message":{"role":"user","content":"another meta line"},"isMeta":true}`,
	}, "\n") + "\n"
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, explicit := parseSessionMeta(path)
	if summary != "" {
		t.Fatalf("summary = %q, want empty for all-meta window", summary)
	}
	if explicit {
		t.Fatal("explicit = true, want false")
	}
}

func TestParseSessionMeta_MetaAfterRealFirstLineDoesNotDisplace(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "session.jsonl")
	jsonl := strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"Real first message"}}`,
		`{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"},"isMeta":true}`,
	}, "\n") + "\n"
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	summary, explicit := parseSessionMeta(path)
	if summary != "Real first message" {
		t.Fatalf("summary = %q, want the real first message to win", summary)
	}
	if explicit {
		t.Fatal("explicit = true, want false")
	}
}

func TestPathToProjectKeyReplacesPathSeparators(t *testing.T) {
	tests := []struct {
		name string
		path string
		want string
	}{
		{
			name: "posix path",
			path: "/Users/dave/Code/.worktrees/foo",
			want: "-Users-dave-Code--worktrees-foo",
		},
		{
			name: "windows path",
			path: `C:\Users\dave\Code\.worktrees\foo`,
			want: "C--Users-dave-Code--worktrees-foo",
		},
		{
			// Regression: a repo registered with a trailing slash must encode
			// to the same key as its clean form, or --resume silently breaks
			// (Claude keys off the normalized getcwd, which has no trailing /).
			name: "posix path with trailing slash",
			path: "/Users/dave/Documents/Code/bossanova/",
			want: "-Users-dave-Documents-Code-bossanova",
		},
		{
			name: "posix path with redundant slashes",
			path: "/Users/dave//Code/foo",
			want: "-Users-dave-Code-foo",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := pathToProjectKey(tt.path)
			if got != tt.want {
				t.Fatalf("pathToProjectKey() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestReadTranscript_BasicMessages(t *testing.T) {
	work := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home)

	key := pathToProjectKey(work)
	dir := filepath.Join(home, ".claude", "projects", key)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	jsonl := `{"type":"user","message":{"role":"user","content":"Hello there"},"timestamp":"2024-01-15T10:00:00Z"}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"Hi! How can I help?"},"timestamp":"2024-01-15T10:00:01Z"}` + "\n" +
		`{"type":"user","message":{"role":"user","content":"Fix the bug"},"timestamp":"2024-01-15T10:00:02Z"}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"Sure, I will fix it."},"timestamp":"2024-01-15T10:00:03Z"}` + "\n"
	if err := os.WriteFile(filepath.Join(dir, "sess.jsonl"), []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(dir, "sess.jsonl")
	messages, finalAssistant, exists, err := readTranscript(path, 0)
	if err != nil {
		t.Fatalf("readTranscript: %v", err)
	}
	if !exists {
		t.Error("exists = false, want true")
	}
	if len(messages) != 4 {
		t.Fatalf("len(messages) = %d, want 4", len(messages))
	}
	if messages[0].Role != "user" {
		t.Errorf("messages[0].Role = %q, want user", messages[0].Role)
	}
	if messages[0].Text != "Hello there" {
		t.Errorf("messages[0].Text = %q, want 'Hello there'", messages[0].Text)
	}
	if messages[0].Timestamp != "2024-01-15T10:00:00Z" {
		t.Errorf("messages[0].Timestamp = %q, want '2024-01-15T10:00:00Z'", messages[0].Timestamp)
	}
	if messages[0].Kind != "text" {
		t.Errorf("messages[0].Kind = %q, want 'text'", messages[0].Kind)
	}
	if messages[1].Role != "assistant" {
		t.Errorf("messages[1].Role = %q, want assistant", messages[1].Role)
	}
	if messages[3].Role != "assistant" {
		t.Errorf("messages[3].Role = %q, want assistant", messages[3].Role)
	}
	if finalAssistant != "Sure, I will fix it." {
		t.Errorf("finalAssistant = %q, want 'Sure, I will fix it.'", finalAssistant)
	}
}

func TestReadTranscript_NoFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "missing.jsonl")

	messages, finalAssistant, exists, err := readTranscript(path, 0)
	if err != nil {
		t.Fatalf("readTranscript: expected nil error for missing file, got %v", err)
	}
	if exists {
		t.Error("exists = true, want false")
	}
	if len(messages) != 0 {
		t.Errorf("len(messages) = %d, want 0", len(messages))
	}
	if finalAssistant != "" {
		t.Errorf("finalAssistant = %q, want empty", finalAssistant)
	}
}

func TestReadTranscript_MaxMessagesTail(t *testing.T) {
	dir := t.TempDir()
	jsonl := `{"type":"user","message":{"role":"user","content":"msg1"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"reply1"}}` + "\n" +
		`{"type":"user","message":{"role":"user","content":"msg2"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"reply2"}}` + "\n"
	path := filepath.Join(dir, "t.jsonl")
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	messages, finalAssistant, exists, err := readTranscript(path, 2)
	if err != nil {
		t.Fatalf("readTranscript: %v", err)
	}
	if !exists {
		t.Error("exists = false, want true")
	}
	if len(messages) != 2 {
		t.Fatalf("len(messages) = %d, want 2 (tail)", len(messages))
	}
	if messages[0].Text != "msg2" {
		t.Errorf("messages[0].Text = %q, want 'msg2'", messages[0].Text)
	}
	if messages[1].Text != "reply2" {
		t.Errorf("messages[1].Text = %q, want 'reply2'", messages[1].Text)
	}
	// FinalAssistantText should reflect the true last assistant turn (reply2).
	if finalAssistant != "reply2" {
		t.Errorf("finalAssistant = %q, want 'reply2'", finalAssistant)
	}
}

func TestReadTranscript_SkipsToolResultOnlyUserEntries(t *testing.T) {
	dir := t.TempDir()
	jsonl := `{"type":"user","message":{"role":"user","content":"hello"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"working on it"}}` + "\n" +
		`{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"ok"}]}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"done"}}` + "\n"
	path := filepath.Join(dir, "t.jsonl")
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	messages, finalAssistant, _, err := readTranscript(path, 0)
	if err != nil {
		t.Fatalf("readTranscript: %v", err)
	}
	// tool_result-only user entry should be skipped → 3 messages
	if len(messages) != 3 {
		t.Fatalf("len(messages) = %d, want 3 (tool_result-only user skipped)", len(messages))
	}
	if finalAssistant != "done" {
		t.Errorf("finalAssistant = %q, want 'done'", finalAssistant)
	}
}

func TestReadTranscript_ViaServer(t *testing.T) {
	work := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home)

	key := pathToProjectKey(work)
	dir := filepath.Join(home, ".claude", "projects", key)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	jsonl := `{"type":"user","message":{"role":"user","content":"help me"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"I can help"}}` + "\n"
	if err := os.WriteFile(filepath.Join(dir, "mysess.jsonl"), []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	srv := &Server{logger: zerolog.Nop()}
	resp, err := srv.ReadTranscript(context.Background(), &bossanovav1.ReadTranscriptRequest{
		WorkDir:        work,
		AgentSessionId: "mysess",
		MaxMessages:    0,
	})
	if err != nil {
		t.Fatalf("ReadTranscript: %v", err)
	}
	if !resp.Exists {
		t.Error("Exists = false, want true")
	}
	if len(resp.Messages) != 2 {
		t.Fatalf("len(Messages) = %d, want 2", len(resp.Messages))
	}
	if resp.FinalAssistantText != "I can help" {
		t.Errorf("FinalAssistantText = %q, want 'I can help'", resp.FinalAssistantText)
	}
}

func TestReadTranscript_ViaServer_MissingFile(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	srv := &Server{logger: zerolog.Nop()}
	resp, err := srv.ReadTranscript(context.Background(), &bossanovav1.ReadTranscriptRequest{
		WorkDir:        t.TempDir(),
		AgentSessionId: "noexist",
	})
	if err != nil {
		t.Fatalf("ReadTranscript should not error on missing file, got: %v", err)
	}
	if resp.Exists {
		t.Error("Exists should be false for missing transcript")
	}
	if len(resp.Messages) != 0 {
		t.Errorf("Messages should be empty for missing transcript, got %d", len(resp.Messages))
	}
	if resp.FinalAssistantText != "" {
		t.Errorf("FinalAssistantText should be empty, got %q", resp.FinalAssistantText)
	}
}

// TestReadTranscript_MaxMessagesTable exercises the maxMessages tail boundary
// (G115): the comparison widens maxMessages (int32 → int) instead of narrowing
// len(all), so the tail cut is correct for zero, in-range, exact-boundary, and
// larger-than-length values and can never wrap.
func TestReadTranscript_MaxMessagesTable(t *testing.T) {
	dir := t.TempDir()
	// 4 real text messages: user, assistant, user, assistant.
	jsonl := `{"type":"user","message":{"role":"user","content":"m1"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"a1"}}` + "\n" +
		`{"type":"user","message":{"role":"user","content":"m2"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"a2"}}` + "\n"
	path := filepath.Join(dir, "tail.jsonl")
	if err := os.WriteFile(path, []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}

	cases := []struct {
		name        string
		maxMessages int32
		wantLen     int
		wantFirst   string
	}{
		{"zero returns all", 0, 4, "m1"},
		{"in-range tail", 2, 2, "m2"},
		{"boundary equals length", 4, 4, "m1"},
		{"larger than length returns all", 100, 4, "m1"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			messages, finalAssistant, exists, err := readTranscript(path, tc.maxMessages)
			if err != nil {
				t.Fatalf("readTranscript: %v", err)
			}
			if !exists {
				t.Fatal("exists = false, want true")
			}
			if len(messages) != tc.wantLen {
				t.Fatalf("len(messages) = %d, want %d", len(messages), tc.wantLen)
			}
			if messages[0].Text != tc.wantFirst {
				t.Errorf("messages[0].Text = %q, want %q", messages[0].Text, tc.wantFirst)
			}
			// finalAssistant always reflects the true last assistant turn.
			if finalAssistant != "a2" {
				t.Errorf("finalAssistant = %q, want %q", finalAssistant, "a2")
			}
		})
	}
}

// TestReadTranscript_UncleanPathLoads confirms the filepath.Clean applied
// before os.Open (G304) does not break loading a valid, internally-derived
// path that arrives un-normalized (redundant separators / dot segments).
func TestReadTranscript_UncleanPathLoads(t *testing.T) {
	dir := t.TempDir()
	jsonl := `{"type":"user","message":{"role":"user","content":"hi"}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":"yo"}}` + "\n"
	if err := os.WriteFile(filepath.Join(dir, "u.jsonl"), []byte(jsonl), 0o600); err != nil {
		t.Fatal(err)
	}
	unclean := dir + string(filepath.Separator) + "." + string(filepath.Separator) + "u.jsonl"
	messages, _, exists, err := readTranscript(unclean, 0)
	if err != nil {
		t.Fatalf("readTranscript(unclean): %v", err)
	}
	if !exists || len(messages) != 2 {
		t.Fatalf("unclean path load: exists=%v len=%d, want true/2", exists, len(messages))
	}
}

// TestTranscriptPathRejectsTraversalSessionID verifies the BOS-415 G304
// root-containment guard on the caller-supplied (req.AgentSessionId) session
// id: an id carrying path separators or ".." is rejected before it is
// interpolated into the ~/.claude/projects path, so a crafted value cannot
// traverse out of the projects root. Mirrors the codex findRolloutPath guard.
func TestTranscriptPathRejectsTraversalSessionID(t *testing.T) {
	for _, id := range []string{"../escape", "a/b", `a\b`, "..", "../../etc/passwd"} {
		if _, err := transcriptPath("/tmp/wt", id); err == nil {
			t.Errorf("transcriptPath(_, %q) = nil error, want rejection", id)
		}
	}
	// A well-formed UUID-shaped id still resolves.
	got, err := transcriptPath("/tmp/wt", "0199-abcd-ef01")
	if err != nil {
		t.Fatalf("transcriptPath valid id: unexpected error %v", err)
	}
	if !strings.HasSuffix(got, "0199-abcd-ef01.jsonl") {
		t.Errorf("transcriptPath valid id = %q, want suffix 0199-abcd-ef01.jsonl", got)
	}
}

// TestChatTitleInDirRejectsTraversalID verifies the BOS-415 G304 guard on the
// GetChatTitle chain: chatTitleInDir rejects a caller-supplied (req.SessionId)
// id carrying path separators or ".." before the join, so a crafted value
// cannot traverse out of the projects dir and read an arbitrary .jsonl file.
// A rename summary planted one level above the projects dir must not leak.
func TestChatTitleInDirRejectsTraversalID(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "projects")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	// Plant a valid, title-bearing rollout one level above projectDir that a
	// traversal id ("../escape") would otherwise resolve into.
	outside := filepath.Join(filepath.Dir(projectDir), "escape.jsonl")
	if err := os.WriteFile(outside, []byte(`{"type":"summary","summary":"leaked"}`+"\n"), 0o600); err != nil {
		t.Fatalf("write outside: %v", err)
	}

	for _, id := range []string{"../escape", "a/b", `a\b`, "..", "../../etc/passwd"} {
		title, explicit := chatTitleInDir(projectDir, id)
		if title != "" || explicit {
			t.Errorf("chatTitleInDir(_, %q) = (%q, %v), want empty rejection", id, title, explicit)
		}
	}

	// A well-formed id still resolves its title normally.
	if err := os.WriteFile(filepath.Join(projectDir, "good.jsonl"),
		[]byte(`{"type":"summary","summary":"real title"}`+"\n"), 0o600); err != nil {
		t.Fatalf("write good: %v", err)
	}
	title, explicit := chatTitleInDir(projectDir, "good")
	if title != "real title" || !explicit {
		t.Errorf("chatTitleInDir valid id = (%q, %v), want (real title, true)", title, explicit)
	}
}
