load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "keyedgate",
    srcs = ["keyedgate.go"],
    importpath = "github.com/recurser/bossalib/keyedgate",
    visibility = ["//visibility:public"],
)

go_test(
    name = "keyedgate_test",
    srcs = ["keyedgate_test.go"],
    embed = [":keyedgate"],
)
