load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "gitremote",
    srcs = [
        "gitremote.go",
        "retry.go",
    ],
    importpath = "github.com/recurser/bossalib/gitremote",
    visibility = ["//visibility:public"],
)

go_test(
    name = "gitremote_test",
    srcs = [
        "gitremote_test.go",
        "retry_test.go",
    ],
    embed = [":gitremote"],
)
