name: proto (lint)

concurrency:
  group:              proto-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - .github/workflows/test-proto.yml
      - proto/**
      - buf.yaml
      - buf.gen.yaml

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.changes.conclusion }}

    steps:
    - uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          proto:
            - .github/workflows/test-proto.yml
            - proto/**
            - buf.yaml
            - buf.gen.yaml

    - name: Check proto changed
      if:  steps.changes.outputs.proto == 'true'
      run: echo "Proto has changed - running CI"

  proto:
    runs-on: ubuntu-latest

    needs: check
    if:    needs.check.outputs.status == 'success'

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - uses: bufbuild/buf-setup-action@v1

    - name: Lint
      run: make lint-proto
