name: lib/bossalib (test)

concurrency:
  group:              lib-bossalib-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - .github/workflows/test-lib-bossalib.yml
      - lib/bossalib/**
      - proto/**

jobs:
  check:
    runs-on: ubicloud

    outputs:
      status: ${{ steps.changes.conclusion }}

    steps:
    - uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          bossalib:
            - .github/workflows/test-lib-bossalib.yml
            - lib/bossalib/**
            - proto/**

    - name: Check library changed
      if:  steps.changes.outputs.bossalib == 'true'
      run: echo "Library has changed - running CI"

  bossalib:
    runs-on: ubicloud

    needs: check
    if:    needs.check.outputs.status == 'success'

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin

    - name: Lint
      run: make lint-bossalib

    - name: Test
      run: make test-bossalib
