name: bossd (test)

concurrency:
  group:              bossd-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - .github/workflows/test-bossd.yml
      - services/bossd/**
      - lib/bossalib/**
      - proto/**

jobs:
  check:
    runs-on: ubicloud

    outputs:
      status: ${{ steps.changes.conclusion }}

    steps:
    - uses: actions/checkout@v6

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          bossd:
            - .github/workflows/test-bossd.yml
            - services/bossd/**
            - lib/bossalib/**
            - proto/**

    - name: Check service changed
      if:  steps.changes.outputs.bossd == 'true'
      run: echo "Service has changed - running CI"

  bossd:
    runs-on: ubicloud

    needs: check
    if:    needs.check.outputs.status == 'success'

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-go@v6
      with:
        go-version: "1.25"

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin

    - name: Lint
      run: make lint-bossd

    - name: Test
      run: make test-bossd

    - name: Build
      run: make build-bossd
